using ODStudio.Model;

namespace ODStudio.Generator;

internal static class OdBehaviorEmitter
{
    public static string Emit(OdGenerationContext context)
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();
        foreach (var group in context.OwnedDefinitions.OfType<OdInterfaceDefinition>()
                     .GroupBy(context.Namespace).OrderBy(item => item.Key, StringComparer.Ordinal))
        {
            using (writer.Block($"namespace {group.Key}"))
            {
                foreach (var definition in group.OrderBy(item => item.Name, StringComparer.Ordinal))
                {
                    EmitInterface(writer, context, definition);
                    writer.Line();
                }
            }
        }
        return writer.ToString();
    }

    public static IEnumerable<OdGeneratedFile> EmitImplementationFiles(OdGenerationContext context)
    {
        foreach (var definition in context.OwnedDefinitions.OfType<OdInterfaceDefinition>()
                     .Where(item => !item.Abstract)
                     .OrderBy(context.Namespace, StringComparer.Ordinal)
                     .ThenBy(item => item.Name, StringComparer.Ordinal))
        {
            yield return new OdGeneratedFile(
                ImplementationPath(context, definition),
                EmitImplementation(context, definition),
                OverwriteExisting: false);
        }
    }

    private static void EmitInterface(CodeWriter writer, OdGenerationContext context, OdInterfaceDefinition definition)
    {
        string name = OdGenerationContext.Identifier(definition.Name);
        EmitPropertyContract(writer, context, definition);
        writer.Line();
        if (definition.Abstract)
            return;

        string paramName = name + "Param";
        string outputName = name + "Result";
        bool isPlayerInput = definition.InterfaceType == OdInterfaceType.PlayerInput;
        bool isLockstep = isPlayerInput && context.Project.Runtime.NetworkMode == OdNetworkMode.Lockstep;
        bool isPredictable = isPlayerInput && !isLockstep && definition.Prediction != OdPredictionMode.None;
        string playerControllerType =
            OdNetworkPackage.PlayerControllerRuntimeTypeName(context.Project.Runtime.NetworkMode);
        const string tryGetPlayerController = "TryGetExecutingPlayerController";
        const string getPlayerController = "GetExecutingPlayerController";
        string proxyType = GameplayMachineProxyType(context.Project);
        string contract = definition.IsRoutine
            ? "global::GMCore.ICheckableRoutine"
            : isPlayerInput && isPredictable
                ? "global::GMCore.IPredictableInterface"
                : isPlayerInput
                ? "global::GMCore.IReplicatedInterface"
                : $"global::GMCore.ICheckableInterface<{outputName}>";

        writer.Line("[global::System.Serializable]");
        string interfaceMarker = isPlayerInput
            ? ", global::GMCore.IPlayerInputInterface"
            : ", global::GMCore.IGameplayInterface";
        using (writer.Block($"public partial struct {paramName} : {contract}, global::GMCore.IODEvent{interfaceMarker}"))
        {
            writer.Line($"public static readonly global::GMCore.ODEventName EventName = new global::GMCore.ODEventName {{ NameObject = {OdGenerationContext.StringLiteral(context.EventStableName(definition))} }};");
            foreach (var input in context.AllInterfaceInputs(definition))
                EmitValueField(writer, context, input, input.NotNull);
            writer.Line("public global::GMCore.ODEventName GetODEventName() => EventName;");
            if (isPlayerInput)
            {
                writer.Line($"public global::GMCore.GameplayRpcMode RpcMode => global::GMCore.GameplayRpcMode.{(isLockstep ? "Lockstep" : isPredictable ? "Predictable" : "Authority")};");
                if (isPredictable)
                    writer.Line($"public global::GMCore.GameplayPredictionMode PredictionMode => global::GMCore.GameplayPredictionMode.{definition.Prediction};");
            }

            string executionContract = isPlayerInput ? "global::GMCore.IReplicatedInterface" : contract;
            using (writer.Block($"global::ODCore.EventError {executionContract}.CanExecute(global::GMCore.GameplayMachine.GameplayMachineProxy machine)"))
            {
                if (isPlayerInput)
                {
                    writer.Line($"var typedMachine = ({proxyType})machine;");
                    writer.Line($"if (!typedMachine.{tryGetPlayerController}(out {playerControllerType} playerController))");
                    writer.Line("    return \"PlayerInput interface requires a PlayerController execution context\";");
                    writer.Line("return CanExecute(typedMachine, playerController, this);");
                }
                else
                {
                    writer.Line($"return CanExecute(({proxyType})machine, this);");
                }
            }

            if (definition.IsRoutine)
            {
                using (writer.Block($"global::System.Collections.IEnumerator {contract}.DoExecute(global::GMCore.GameplayMachine.GameplayMachineProxy machine)"))
                    writer.Line(isPlayerInput
                        ? $"return DoExecute(({proxyType})machine, (({proxyType})machine).{getPlayerController}(), this);"
                        : $"return DoExecute(({proxyType})machine, this);");
            }
            else if (isPlayerInput)
            {
                using (writer.Block($"void {executionContract}.DoExecute(global::GMCore.GameplayMachine.GameplayMachineProxy machine)"))
                    writer.Line($"DoExecute(({proxyType})machine, (({proxyType})machine).{getPlayerController}(), this);");
                if (isPredictable)
                {
                    using (writer.Block("void global::GMCore.IPredictableInterface.OnPredictClient(global::GMCore.GameplayMachine.GameplayMachineProxy machine)"))
                        writer.Line($"OnPredictClient(({proxyType})machine, this);");
                    using (writer.Block("void global::GMCore.IPredictableInterface.OnSuccessClient(global::GMCore.GameplayMachine.GameplayMachineProxy machine)"))
                        if (ReportsSuccess(definition.Prediction))
                            writer.Line($"OnSuccessClient(({proxyType})machine, this);");
                    using (writer.Block("void global::GMCore.IPredictableInterface.OnFailClient(global::GMCore.GameplayMachine.GameplayMachineProxy machine)"))
                        if (ReportsFailure(definition.Prediction))
                            writer.Line($"OnFailClient(({proxyType})machine, this);");
                }
            }
            else
            {
                using (writer.Block($"void {contract}.DoExecute(global::GMCore.GameplayMachine.GameplayMachineProxy machine, ref {outputName} outResult)"))
                    writer.Line($"DoExecute(({proxyType})machine, this, ref outResult);");
            }
        }

        if (!definition.IsRoutine && !isPlayerInput)
        {
            writer.Line("[global::System.Serializable]");
            using (writer.Block($"public partial struct {outputName}"))
                foreach (var output in definition.Outputs)
                    EmitValueField(writer, context, output);
        }

        if (IsCallableValue(definition))
        {
            writer.Line();
            EmitCallClass(writer, context, definition);
        }

    }

    private static void EmitPropertyContract(CodeWriter writer, OdGenerationContext context,
        OdInterfaceDefinition definition)
    {
        string name = OdGenerationContext.SafeIdentifier(definition.Name).TrimStart('@');
        string contractName = "I" + name;
        string? baseContract = definition.BaseInterfaceId is { } baseId &&
                               context.Definitions.TryGetValue(baseId, out OdDefinition? baseDefinition) &&
                               baseDefinition is OdInterfaceDefinition baseInterface
            ? context.InterfaceContractTypeName(baseInterface)
            : null;
        bool callable = IsCallableValue(definition);
        string inheritance = baseContract ?? (callable ? "global::GMCore.IODInterfaceCall" : string.Empty);
        using (writer.Block($"public interface {contractName}{(inheritance.Length == 0 ? string.Empty : " : " + inheritance)}"))
        {
            foreach (OdFieldDefinition input in definition.Inputs)
                writer.Line($"{context.FieldTypeName(input)} {OdGenerationContext.Identifier(input.Name)} {{ get; set; }}");
            if (callable)
                writer.Line($"{(baseContract is null ? string.Empty : "new ")}{context.InterfaceContractTypeName(definition)} Copy();");
        }
    }

    private static void EmitCallClass(CodeWriter writer, OdGenerationContext context,
        OdInterfaceDefinition definition)
    {
        string name = OdGenerationContext.SafeIdentifier(definition.Name);
        string contract = context.InterfaceContractTypeName(definition);
        IReadOnlyList<OdFieldDefinition> inputs = context.AllInterfaceInputs(definition);
        writer.Line("[global::System.Serializable]");
        using (writer.Block($"public sealed class {name}Call : {contract}"))
        {
            foreach (OdFieldDefinition input in inputs)
            {
                string initializer = input.Type.Container != OdContainerKind.Single
                    ? $" = new {context.FieldTypeName(input, includeNullable: false)}();"
                    : input.Type.BuiltIn == OdBuiltInType.String && input.Type.DefinitionId is null && !input.Type.Nullable
                        ? " = global::System.String.Empty;"
                        : string.Empty;
                writer.Line($"public {context.FieldTypeName(input)} {OdGenerationContext.Identifier(input.Name)} {{ get; set; }}{initializer}");
            }
            writer.Line($"public ulong InterfaceID => global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(context.EventStableName(definition))});");
            writer.Line("public global::GMCore.GameplayInterfaceType InterfaceType => global::GMCore.GameplayInterfaceType.Gameplay;");
            string assignments = string.Join(", ", inputs.Select(input =>
                $"{OdGenerationContext.Identifier(input.Name)} = {CloneExpression(context, input)}"));
            writer.Line($"public {contract} Copy() => new {name}Call {{ {assignments} }};");
            foreach (OdInterfaceDefinition ancestor in context.InterfaceHierarchy(definition).SkipLast(1))
                writer.Line($"{context.InterfaceContractTypeName(ancestor)} {context.InterfaceContractTypeName(ancestor)}.Copy() => Copy();");
            writer.Line("global::GMCore.IODInterfaceCall global::GMCore.IODInterfaceCall.CopyUntyped() => Copy();");
            using (writer.Block("global::ODCore.EventError global::GMCore.IODInterfaceCall.CanExecute(global::GMCore.GameplayMachine.GameplayMachineProxy machine)"))
            {
                foreach (OdFieldDefinition input in inputs.Where(input => input.NotNull && context.IsLiveClassReference(input)))
                {
                    string member = OdGenerationContext.Identifier(input.Name);
                    writer.Line($"if (!{member}.HasValue) return {OdGenerationContext.StringLiteral($"Interface call input '{input.Name}' cannot be null")};");
                }
                string paramAssignments = string.Join(", ", inputs.Select(input =>
                {
                    string member = OdGenerationContext.Identifier(input.Name);
                    return $"{member} = {(input.NotNull && context.IsLiveClassReference(input) ? member + ".Value" : member)}";
                }));
                writer.Line($"return machine.CanExecute<{name}Result>(new {name}Param {{ {paramAssignments} }});");
            }
            using (writer.Block("global::GMCore.CheckableInterfaceResult global::GMCore.IODInterfaceCall.Invoke(global::GMCore.GameplayMachine.GameplayMachineProxy machine)"))
            {
                foreach (OdFieldDefinition input in inputs.Where(input => input.NotNull && context.IsLiveClassReference(input)))
                {
                    string member = OdGenerationContext.Identifier(input.Name);
                    writer.Line($"if (!{member}.HasValue) return new global::GMCore.CheckableInterfaceResult {{ ErrorMessage = {OdGenerationContext.StringLiteral($"Interface call input '{input.Name}' cannot be null")} }};");
                }
                string paramAssignments = string.Join(", ", inputs.Select(input =>
                {
                    string member = OdGenerationContext.Identifier(input.Name);
                    return $"{member} = {(input.NotNull && context.IsLiveClassReference(input) ? member + ".Value" : member)}";
                }));
                writer.Line($"global::GMCore.CheckableInterfaceResult<{name}Result> result = machine.Execute<{name}Result>(new {name}Param {{ {paramAssignments} }});");
                writer.Line("return result.CheckableResult;");
            }
        }
    }

    private static string CloneExpression(OdGenerationContext context, OdFieldDefinition input)
    {
        string member = OdGenerationContext.Identifier(input.Name);
        if (input.Type.Container == OdContainerKind.Single)
            return member;
        string type = context.FieldTypeName(input, includeNullable: false);
        return $"{member} is null ? null : new {type}({member})";
    }

    private static bool IsCallableValue(OdInterfaceDefinition definition) =>
        definition.InterfaceType == OdInterfaceType.Gameplay && !definition.IsRoutine && definition.Outputs.Count == 0;

    private static void EmitValueField(CodeWriter writer, OdGenerationContext context, OdFieldDefinition field,
        bool notNull = false)
    {
        bool notNullClass = notNull && context.IsLiveClassReference(field);
        string type = context.FieldTypeName(field, includeNullable: !notNullClass);
        string name = OdGenerationContext.Identifier(field.Name);
        if (notNullClass)
        {
            writer.Line("[global::System.Diagnostics.CodeAnalysis.NotNull]");
            writer.Line($"public {type} {name};");
            return;
        }
        if (!context.IsLiveClassReference(field))
        {
            writer.Line($"public {type} {name};");
            return;
        }

        string backingName = $"__reference_{field.Id:N}";
        writer.Line($"private {type} {backingName};");
        writer.Line($"public {type} {name} {{ get => global::GMCore.GameplayMachine.ResolveGameplayObjectReference({backingName}); set => {backingName} = value; }}");
    }

    internal static string EmitImplementation(OdGenerationContext context, OdInterfaceDefinition definition)
    {
        var writer = new CodeWriter();
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Collections;");
        writer.Line("using GMCore;");
        writer.Line("using ODCore;");
        if (definition.InterfaceType == OdInterfaceType.PlayerInput)
            writer.Line($"using {OdNetworkPackage.PlayerControllerNamespace(context.Project.Runtime.NetworkMode)};");
        writer.Line();
        string name = OdGenerationContext.Identifier(definition.Name);
        string paramName = name + "Param";
        string outputName = name + "Result";
        bool isPlayerInput = definition.InterfaceType == OdInterfaceType.PlayerInput;
        bool isLockstep = isPlayerInput && context.Project.Runtime.NetworkMode == OdNetworkMode.Lockstep;
        bool isPredictable = isPlayerInput && !isLockstep && definition.Prediction != OdPredictionMode.None;
        string proxyType = $"{OdProjectCodeManager.SafeProjectName(context.Project)}GameplayMachineProxy";
        string playerParameter = isPlayerInput ? ", PlayerController playerController" : string.Empty;

        using (writer.Block($"namespace {context.Namespace(definition)}"))
        using (writer.Block($"public partial struct {paramName}"))
        {
            using (writer.Block($"private static EventError CanExecute({proxyType} machine{playerParameter}, {paramName} input)"))
                writer.Line("throw new NotImplementedException();");

            if (definition.IsRoutine)
            {
                using (writer.Block($"private static IEnumerator DoExecute({proxyType} machine{playerParameter}, {paramName} input)"))
                    writer.Line("throw new NotImplementedException();");
            }
            else if (isPlayerInput)
            {
                using (writer.Block($"private static void DoExecute({proxyType} machine{playerParameter}, {paramName} input)"))
                    writer.Line("throw new NotImplementedException();");
                if (isPredictable)
                {
                    using (writer.Block($"private static void OnPredictClient({proxyType} machine, {paramName} input)"))
                    {
                    }
                    if (ReportsSuccess(definition.Prediction))
                        using (writer.Block($"private static void OnSuccessClient({proxyType} machine, {paramName} input)"))
                        {
                        }
                    if (ReportsFailure(definition.Prediction))
                        using (writer.Block($"private static void OnFailClient({proxyType} machine, {paramName} input)"))
                        {
                        }
                }
            }
            else
            {
                using (writer.Block($"private static void DoExecute({proxyType} machine{playerParameter}, {paramName} input, ref {outputName} outResult)"))
                    writer.Line("throw new NotImplementedException();");
            }
        }
        return writer.ToString();
    }

    private static bool ReportsSuccess(OdPredictionMode mode) =>
        mode is OdPredictionMode.OnlySuccess or OdPredictionMode.Both;

    private static bool ReportsFailure(OdPredictionMode mode) =>
        mode is OdPredictionMode.OnlyFailure or OdPredictionMode.Both;

    internal static string ImplementationPath(OdGenerationContext context, OdInterfaceDefinition definition)
    {
        return $"Interfaces/{OdGenerationContext.SafeIdentifier(definition.Name)}Param.cs";
    }

    private static string GameplayMachineProxyType(OdProject project) =>
        $"global::{OdGenerationContext.NamespaceIdentifier(project.DefaultNamespace)}.{OdProjectCodeManager.SafeProjectName(project)}GameplayMachineProxy";

}
