using ODStudio.Model;

namespace ODStudio.Generator;

internal static class OdModuleEmitter
{
    public static string Emit(OdGenerationContext context)
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();
        using (writer.Block($"namespace {context.RootNamespace}"))
        {
            using (writer.Block($"public sealed partial class {context.ModuleTypeName} : global::GMCore.IODModule, global::GMCore.IODNetworkModule, global::GMCore.IODMulticastEventNetworkModule, global::GMCore.IODResourceCatalogNetworkModule, global::GMCore.IODDebugModule"))
            {
                writer.Line($"public global::GMCore.ODModuleName Name => new global::GMCore.ODModuleName {{ Name = {OdGenerationContext.StringLiteral(context.ModuleStableName)} }};");
                writer.Line();
                EmitClassMetas(writer, context);
                writer.Line();
                EmitStructMetas(writer, context);
                writer.Line();
                EmitEventMetas(writer, context);
                writer.Line();
                EmitClassSaveMetas(writer, context);
                writer.Line();
                EmitFieldSaveMetas(writer, context);
                writer.Line();
                EmitNetworkSchema(writer, context);
                writer.Line();
                EmitRpcMetas(writer, context);
                writer.Line();
                EmitMulticastEventMetas(writer, context);
                writer.Line();
                EmitCodecs(writer, context);
                writer.Line();
                EmitRpcCodecs(writer, context);
                writer.Line();
                EmitMulticastEventCodecs(writer, context);
                writer.Line();
                EmitDebugMetadata(writer, context);
            }
        }
        return writer.ToString();
    }

    private static void EmitClassMetas(CodeWriter writer, OdGenerationContext context)
    {
        using (writer.Block("public global::System.Collections.Generic.IEnumerable<global::GMCore.ODClassMeta> GetAllODClassMetas()"))
        {
            foreach (var definition in context.OwnedDefinitions.OfType<OdClassDefinition>())
            {
                writer.Line("yield return new global::GMCore.ODClassMeta");
                writer.Line("{");
                writer.Line("    FromModule = Name,");
                writer.Line($"    Name = {context.FullName(definition)}.ClassName,");
                writer.Line($"    ODType = typeof({context.FullName(definition)}),");
                writer.Line($"    ReplicationMode = global::GMCore.GameplayObjectReplicationMode.{definition.Replication},");
                writer.Line($"    RelevancyMode = global::GMCore.GameplayObjectRelevancyMode.{definition.Relevancy},");
                OdObjectPartitionMode partitionMode = context.Project.Runtime.NetworkMode == OdNetworkMode.Lockstep
                    ? OdObjectPartitionMode.Manual
                    : definition.Partition;
                writer.Line($"    PartitionMode = global::GMCore.GameplayObjectPartitionMode.{partitionMode},");
                writer.Line($"    IsEngineManaged = {(context.Project.RootClassId == definition.Id ? "true" : "false")},");
                var directBases = definition.IsClasses.Select(id =>
                    context.Definitions.TryGetValue(id, out var baseDefinition) && baseDefinition is OdClassDefinition
                        ? $"{context.FullName(baseDefinition)}.ClassName"
                        : null).Where(item => item is not null).ToList();
                string baseItems = string.Join(", ", directBases);
                string bases = baseItems.Length > 0
                    ? $"new global::System.Collections.Generic.List<global::GMCore.ODClassName> {{ {baseItems} }}"
                    : "new global::System.Collections.Generic.List<global::GMCore.ODClassName>()";
                writer.Line($"    DirectBaseClasses = {bases},");
                writer.Line("    Fields = new global::System.Collections.Generic.List<global::GMCore.ODFieldMeta>");
                writer.Line("    {");
                foreach (var field in definition.Fields)
                {
                    string fieldRef = $"{context.FullName(definition)}.Fields.{OdGenerationContext.Identifier(field.Name)}";
                    writer.Line("        new global::GMCore.ODFieldMeta");
                    writer.Line("        {");
                    writer.Line($"            FromClass = {context.FullName(definition)}.ClassName,");
                    writer.Line($"            Name = {fieldRef},");
                    if (field.Type.Container != OdContainerKind.Single)
                    {
                        string proxyType = context.FieldTypeName(field, gameplayCollection: true);
                        writer.Line($"            DefaultObject = default({proxyType}),");
                        writer.Line($"            FieldType = typeof({proxyType}),");
                        writer.Line($"            InitialValueFactory = () => {context.CollectionStorageExpression(field)},");
                    }
                    else
                    {
                        writer.Line($"            DefaultObject = {context.DefaultExpression(field)},");
                        writer.Line($"            FieldType = typeof({context.FieldTypeName(field, includeNullable: false)}),");
                    }
                    writer.Line($"            ReplicationMode = global::GMCore.ODFieldReplicationMode.{field.Replication},");
                    writer.Line($"            IsDriven = {(field.Mode == OdFieldMode.Driven ? "true" : "false")},");
                    string drivenBys = FieldReferences(context, context.BaseDrivenByFields(definition, field));
                    string drivingOfs = FieldReferences(context, context.FinalDrivingFields(field));
                    writer.Line($"            DrivenBys = new global::System.Collections.Generic.List<global::GMCore.ODFieldName> {{ {drivenBys} }},");
                    writer.Line($"            DrivingOfs = new global::System.Collections.Generic.List<global::GMCore.ODFieldName> {{ {drivingOfs} }},");
                    writer.Line("        },");
                }
                writer.Line("    },");
                writer.Line("};");
            }
            writer.Line("yield break;");
        }
    }

    private static void EmitStructMetas(CodeWriter writer, OdGenerationContext context)
    {
        using (writer.Block("public global::System.Collections.Generic.IEnumerable<global::GMCore.ODStructMeta> GetAllODStructMetas()"))
        {
            foreach (var definition in context.OwnedDefinitions
                         .Where(item => item is OdResourceDefinition or OdSwitchStructDefinition ||
                                        item is OdStructDefinition structDefinition && context.ShouldEmitStructMetadata(structDefinition)))
            {
                string baseStruct = "null";
                string baseType = "null";
                if (definition is OdStructDefinition { IsStructOf: { } aliasType })
                {
                    baseType = $"typeof({context.TypeName(aliasType, false)})";
                    if (aliasType.DefinitionId is { } targetId &&
                        context.Definitions.TryGetValue(targetId, out OdDefinition? targetDefinition) &&
                        targetDefinition is OdStructDefinition)
                        baseStruct = $"{context.FullName(targetDefinition)}.StructName";
                }
                writer.Line("yield return new global::GMCore.ODStructMeta");
                writer.Line("{");
                writer.Line("    FromModule = Name,");
                writer.Line($"    Name = {context.FullName(definition)}.StructName,");
                writer.Line($"    ODType = typeof({context.FullName(definition)}),");
                writer.Line($"    BaseStruct = {baseStruct},");
                writer.Line($"    BaseType = {baseType},");
                writer.Line("};");
            }
            writer.Line("yield break;");
        }
    }

    private static void EmitEventMetas(CodeWriter writer, OdGenerationContext context)
    {
        using (writer.Block("public global::System.Collections.Generic.IEnumerable<global::GMCore.ODEventMeta> GetAllODEventMetas()"))
        {
            foreach (var definition in context.OwnedDefinitions.OfType<OdEventDefinition>())
                writer.Line($"yield return new global::GMCore.ODEventMeta {{ FromModule = Name, Name = {context.FullName(definition)}.EventName, ODType = typeof({context.FullName(definition)}), Multicast = {(definition.Multicast ? "true" : "false")} }};");
            foreach (var definition in context.OwnedDefinitions.OfType<OdInterfaceDefinition>().Where(item => !item.Abstract))
                writer.Line($"yield return new global::GMCore.ODEventMeta {{ FromModule = Name, Name = global::{context.Namespace(definition)}.{OdGenerationContext.Identifier(definition.Name)}Param.EventName, ODType = typeof(global::{context.Namespace(definition)}.{OdGenerationContext.Identifier(definition.Name)}Param) }};");
            writer.Line("yield break;");
        }
    }

    private static void EmitClassSaveMetas(CodeWriter writer, OdGenerationContext context)
    {
        using (writer.Block("public global::System.Collections.Generic.IEnumerable<global::GMCore.ODClassSaveMeta> GetAllODClassSaveMetas()"))
        {
            foreach (var definition in context.OwnedDefinitions.OfType<OdClassDefinition>())
            {
                string stableName = context.ClassStableName(definition);
                writer.Line($"yield return new global::GMCore.ODClassSaveMeta {{ StableID = global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(stableName)}), StableName = {OdGenerationContext.StringLiteral(stableName)}, ClassName = {context.FullName(definition)}.ClassName }};");
            }
            writer.Line("yield break;");
        }
    }

    private static void EmitFieldSaveMetas(CodeWriter writer, OdGenerationContext context)
    {
        using (writer.Block("public global::System.Collections.Generic.IEnumerable<global::GMCore.ODFieldSaveMeta> GetAllODFieldSaveMetas()"))
        {
            foreach (var owner in context.OwnedDefinitions.OfType<OdClassDefinition>())
                foreach (var field in owner.Fields.Where(item => item.Mode != OdFieldMode.Driven))
                {
                    string suffix = $"{owner.Id:N}_{field.Id:N}";
                    string stableName = context.FieldStableName(owner, field);
                    string deltaMembers = field.Type.Container switch
                    {
                        OdContainerKind.Set => $", DeltaKind = global::GMCore.ODCollectionDeltaKind.Set, DeltaKeyWriter = WriteDeltaKey_{suffix}, DeltaKeyReader = ReadDeltaKey_{suffix}",
                        OdContainerKind.Dictionary => $", DeltaKind = global::GMCore.ODCollectionDeltaKind.Map, DeltaKeyWriter = WriteDeltaKey_{suffix}, DeltaKeyReader = ReadDeltaKey_{suffix}, DeltaValueWriter = WriteDeltaValue_{suffix}, DeltaValueReader = ReadDeltaValue_{suffix}",
                        _ => string.Empty,
                    };
                    writer.Line($"yield return new global::GMCore.ODFieldSaveMeta {{ StableID = global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(stableName)}), StableName = {OdGenerationContext.StringLiteral(stableName)}, FieldName = {context.FullName(owner)}.Fields.{OdGenerationContext.Identifier(field.Name)}, Writer = Write_{suffix}, Reader = Read_{suffix}{deltaMembers} }};");
                }
            writer.Line("yield break;");
        }
    }

    private static void EmitNetworkSchema(CodeWriter writer, OdGenerationContext context)
    {
        string signature = BuildNetworkSchemaSignature(context);
        writer.Line($"public ulong NetworkSchemaID => global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(signature)});");
        writer.Line($"public ulong ResourceCatalogID => {ResourceCatalogIdExpression(context)};");
    }

    private static string ResourceCatalogIdExpression(OdGenerationContext context)
    {
        if (context.Options.ResourceCatalogIdExpression is { } configured)
            return configured;

        string signature = OdResourceCatalog.BuildSignature(context.Project);
        return $"global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(signature)})";
    }

    private static void EmitRpcMetas(CodeWriter writer, OdGenerationContext context)
    {
        using (writer.Block("public global::System.Collections.Generic.IEnumerable<global::GMCore.ODRpcMeta> GetAllODRpcMetas()"))
        {
            foreach (var definition in NetworkInterfaces(context))
            {
                string name = OdGenerationContext.Identifier(definition.Name);
                string suffix = definition.Id.ToString("N");
                string stableName = RpcStableName(context, definition);
                string scope = $"global::{context.Namespace(definition)}";
                writer.Line("yield return new global::GMCore.ODRpcMeta");
                writer.Line("{");
                writer.Line($"    StableID = global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(stableName)}),");
                writer.Line($"    StableName = {OdGenerationContext.StringLiteral(stableName)},");
                string rpcMode = context.Project.Runtime.NetworkMode == OdNetworkMode.Lockstep
                    ? "Lockstep"
                    : definition.Prediction == OdPredictionMode.None ? "Authority" : "Predictable";
                writer.Line($"    Mode = global::GMCore.GameplayRpcMode.{rpcMode},");
                writer.Line("    InterfaceType = global::GMCore.GameplayInterfaceType.PlayerInput,");
                writer.Line($"    ParamType = typeof({scope}.{name}Param),");
                writer.Line($"    ParamWriter = WriteRpcParam_{suffix},");
                writer.Line($"    ParamReader = ReadRpcParam_{suffix},");
                writer.Line("};");
            }
            writer.Line("yield break;");
        }
    }

    private static void EmitMulticastEventMetas(CodeWriter writer, OdGenerationContext context)
    {
        using (writer.Block("public global::System.Collections.Generic.IEnumerable<global::GMCore.ODMulticastEventMeta> GetAllODMulticastEventMetas()"))
        {
            foreach (OdEventDefinition definition in MulticastEvents(context))
            {
                string suffix = definition.Id.ToString("N");
                string stableName = context.EventStableName(definition);
                writer.Line("yield return new global::GMCore.ODMulticastEventMeta");
                writer.Line("{");
                writer.Line($"    StableID = global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(stableName)}),");
                writer.Line($"    StableName = {OdGenerationContext.StringLiteral(stableName)},");
                writer.Line($"    EventType = typeof({context.FullName(definition)}),");
                writer.Line($"    Writer = WriteMulticastEvent_{suffix},");
                writer.Line($"    Reader = ReadMulticastEvent_{suffix},");
                writer.Line("};");
            }
            writer.Line("yield break;");
        }
    }

    private static void EmitCodecs(CodeWriter writer, OdGenerationContext context)
    {
        foreach (var owner in context.OwnedDefinitions.OfType<OdClassDefinition>())
            foreach (var field in owner.Fields.Where(item => item.Mode != OdFieldMode.Driven))
            {
                string suffix = $"{owner.Id:N}_{field.Id:N}";
                string typeName = context.FieldTypeName(field);
                using (writer.Block($"private static void Write_{suffix}(global::GMCore.GameplaySaveWriter writer, object boxedValue)"))
                {
                    writer.Line($"{typeName} value = ({typeName})boxedValue;");
                    var codec = new CodecWriter(writer, context);
                    codec.Write(field, "value");
                }
                using (writer.Block($"private static object Read_{suffix}(global::GMCore.GameplaySaveReader reader)"))
                {
                    var codec = new CodecWriter(writer, context);
                    string value = codec.Read(field);
                    writer.Line($"return {value}!;");
                }
                if (field.Type.Container is OdContainerKind.Set or OdContainerKind.Dictionary)
                {
                    OdTypeReference keyType = field.Type.Container == OdContainerKind.Set
                        ? ElementType(field.Type)
                        : DictionaryKeyType(field.Type);
                    EmitDeltaCodec(writer, context, suffix, "Key", keyType,
                        classNotNull: field.Type.Container == OdContainerKind.Dictionary);
                }
                if (field.Type.Container == OdContainerKind.Dictionary)
                    EmitDeltaCodec(writer, context, suffix, "Value", ElementType(field.Type));
            }
    }

    private static void EmitDeltaCodec(
        CodeWriter writer,
        OdGenerationContext context,
        string suffix,
        string part,
        OdTypeReference type,
        bool classNotNull = false)
    {
        string typeName = context.TypeName(type, includeNullable: !classNotNull);
        using (writer.Block($"private static void WriteDelta{part}_{suffix}(global::GMCore.GameplaySaveWriter writer, object boxedValue)"))
        {
            writer.Line($"{typeName} value = ({typeName})boxedValue;");
            new CodecWriter(writer, context).Write(type, "value", classNotNull);
        }
        using (writer.Block($"private static object ReadDelta{part}_{suffix}(global::GMCore.GameplaySaveReader reader)"))
        {
            string value = new CodecWriter(writer, context).Read(type, classNotNull);
            writer.Line($"return {value}!;");
        }
    }

    private static OdTypeReference ElementType(OdTypeReference type) => new()
    {
        BuiltIn = type.BuiltIn,
        DefinitionId = type.DefinitionId,
        IsResourceClass = type.IsResourceClass,
        Nullable = type.Nullable,
    };

    private static OdTypeReference DictionaryKeyType(OdTypeReference type) => new()
    {
        BuiltIn = type.DictionaryKeyBuiltIn,
        DefinitionId = type.DictionaryKeyDefinitionId,
        IsResourceClass = type.DictionaryKeyIsResourceClass,
    };

    private static void EmitRpcCodecs(CodeWriter writer, OdGenerationContext context)
    {
        foreach (var definition in NetworkInterfaces(context))
        {
            string name = OdGenerationContext.Identifier(definition.Name);
            string suffix = definition.Id.ToString("N");
            string scope = $"global::{context.Namespace(definition)}";
            string paramType = $"{scope}.{name}Param";

            using (writer.Block($"private static void WriteRpcParam_{suffix}(global::GMCore.GameplaySaveWriter writer, object boxedValue)"))
            {
                writer.Line($"{paramType} value = ({paramType})boxedValue;");
                var codec = new CodecWriter(writer, context);
                foreach (var field in context.AllInterfaceInputs(definition))
                    codec.Write(field, $"value.{OdGenerationContext.Identifier(field.Name)}", field.NotNull);
            }
            using (writer.Block($"private static object ReadRpcParam_{suffix}(global::GMCore.GameplaySaveReader reader)"))
            {
                writer.Line($"{paramType} result = default;");
                var codec = new CodecWriter(writer, context);
                foreach (var field in context.AllInterfaceInputs(definition))
                {
                    string value = codec.Read(field, field.NotNull);
                    writer.Line($"result.{OdGenerationContext.Identifier(field.Name)} = {value};");
                }
                writer.Line("return result;");
            }
        }
    }

    private static IEnumerable<OdInterfaceDefinition> NetworkInterfaces(OdGenerationContext context) =>
        context.OwnedDefinitions.OfType<OdInterfaceDefinition>()
            .Where(item => !item.Abstract && item.InterfaceType == OdInterfaceType.PlayerInput)
            .OrderBy(item => item.Id);

    private static IEnumerable<OdEventDefinition> MulticastEvents(OdGenerationContext context) =>
        context.OwnedDefinitions.OfType<OdEventDefinition>()
            .Where(item => item.Multicast)
            .OrderBy(item => item.Id);

    private static void EmitMulticastEventCodecs(CodeWriter writer, OdGenerationContext context)
    {
        foreach (OdEventDefinition definition in MulticastEvents(context))
        {
            string suffix = definition.Id.ToString("N");
            string eventType = context.FullName(definition);
            using (writer.Block($"private static void WriteMulticastEvent_{suffix}(global::GMCore.GameplaySaveWriter writer, object boxedValue)"))
            {
                writer.Line($"{eventType} value = ({eventType})boxedValue;");
                var codec = new CodecWriter(writer, context);
                foreach (OdFieldDefinition field in definition.Fields)
                    codec.Write(field, $"value.{OdGenerationContext.Identifier(field.Name)}", field.NotNull);
            }
            using (writer.Block($"private static object ReadMulticastEvent_{suffix}(global::GMCore.GameplaySaveReader reader)"))
            {
                writer.Line($"{eventType} result = default;");
                var codec = new CodecWriter(writer, context);
                foreach (OdFieldDefinition field in definition.Fields)
                {
                    string value = codec.Read(field, field.NotNull);
                    writer.Line($"result.{OdGenerationContext.Identifier(field.Name)} = {value};");
                }
                writer.Line("return result;");
            }
        }
    }

    private static void EmitDebugMetadata(CodeWriter writer, OdGenerationContext context)
    {
        string signature = BuildDebugSchemaSignature(context);
        writer.Line($"public ulong DebugSchemaID => global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(signature)});");
        writer.Line();
        using (writer.Block("public global::System.Collections.Generic.IEnumerable<global::GMCore.ODDebugClassMeta> GetAllODDebugClassMetas()"))
        {
            foreach (OdClassDefinition definition in context.OwnedDefinitions.OfType<OdClassDefinition>())
            {
                writer.Line("yield return new global::GMCore.ODDebugClassMeta");
                writer.Line("{");
                writer.Line($"    StableID = global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(context.ClassStableName(definition))}),");
                writer.Line($"    StableName = {OdGenerationContext.StringLiteral(context.ClassStableName(definition))},");
                writer.Line($"    DisplayName = {OdGenerationContext.StringLiteral(definition.Name)},");
                writer.Line($"    ClassName = {context.FullName(definition)}.ClassName,");
                writer.Line($"    IsEngineManaged = {(context.Project.RootClassId == definition.Id ? "true" : "false")},");
                string assignableClassIDs = string.Join(", ", context.AllAssignableClasses(definition)
                    .Select(item => $"global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(context.ClassStableName(item))})"));
                writer.Line($"    AssignableClassIDs = new global::System.Collections.Generic.List<ulong> {{ {assignableClassIDs} }},");
                writer.Line("    Fields = new global::System.Collections.Generic.List<global::GMCore.ODDebugFieldMeta>");
                writer.Line("    {");
                foreach ((OdClassDefinition owner, OdFieldDefinition field) in context.AllFields(definition))
                {
                    string member = OdGenerationContext.Identifier(field.Name);
                    string valueType = DebugValueTypeName(context, field.Type);
                    string keyType = field.Type.Container == OdContainerKind.Dictionary
                        ? $"typeof({DebugKeyTypeName(context, field.Type)})"
                        : "null";
                    writer.Line("        new global::GMCore.ODDebugFieldMeta");
                    writer.Line("        {");
                    writer.Line($"            StableID = global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(context.FieldStableName(owner, field))}),");
                    writer.Line($"            StableName = {OdGenerationContext.StringLiteral(context.FieldStableName(owner, field))},");
                    writer.Line($"            DisplayName = {OdGenerationContext.StringLiteral(field.Name)},");
                    writer.Line($"            FieldName = {context.FullName(owner)}.Fields.{member},");
                    writer.Line($"            ValueType = typeof({valueType}),");
                    writer.Line($"            KeyType = {keyType},");
                    writer.Line($"            Container = global::GMCore.GameplayDebugContainerKind.{DebugContainer(field.Type.Container)},");
                    writer.Line($"            IsGameplayObjectReference = {(context.IsClassReference(field.Type) ? "true" : "false")},");
                    writer.Line($"            GameplayObjectClassID = {DebugClassReferenceID(context, field.Type)},");
                    writer.Line($"            IsResourceReference = {(DebugResourceDefinition(context, field.Type) is not null ? "true" : "false")},");
                    writer.Line($"            IsResourceKeyReference = {(field.Type.Container == OdContainerKind.Dictionary && DebugResourceDefinition(context, DebugKeyType(field.Type)) is not null ? "true" : "false")},");
                    writer.Line($"            ResourceOptions = {DebugResourceOptions(context, field.Type)},");
                    writer.Line($"            ResourceKeyOptions = {(field.Type.Container == OdContainerKind.Dictionary ? DebugResourceOptions(context, DebugKeyType(field.Type)) : "null")},");
                    writer.Line($"            IsDriven = {(field.Mode == OdFieldMode.Driven ? "true" : "false")},");
                    writer.Line($"            ReplicationMode = global::GMCore.ODFieldReplicationMode.{field.Replication},");
                    writer.Line($"            Read = (machine, objectID) => (object)machine.GetGameplayObject<{context.FullName(definition)}>(objectID).{member}!,");
                    if (field.Mode != OdFieldMode.Driven && field.Type.Container == OdContainerKind.Single)
                    {
                        writer.Line("            Write = (machine, objectID, value) =>");
                        writer.Line("            {");
                        writer.Line($"                {context.FullName(definition)} target = machine.GetGameplayObject<{context.FullName(definition)}>(objectID);");
                        writer.Line($"                target.{member} = ({context.FieldTypeName(field)})value!;");
                        writer.Line("            },");
                    }
                    writer.Line("        },");
                }
                writer.Line("    },");
                writer.Line("};");
            }
            writer.Line("yield break;");
        }

        writer.Line();
        using (writer.Block("public global::System.Collections.Generic.IEnumerable<global::GMCore.ODDebugInterfaceMeta> GetAllODDebugInterfaceMetas()"))
        {
            foreach (OdInterfaceDefinition definition in context.OwnedDefinitions.OfType<OdInterfaceDefinition>().Where(item => !item.Abstract).OrderBy(item => item.Id))
            {
                string name = OdGenerationContext.Identifier(definition.Name);
                string scope = $"global::{context.Namespace(definition)}";
                string stableName = $"{context.ModuleStableName}:interface:{definition.Id:N}";
                writer.Line("yield return new global::GMCore.ODDebugInterfaceMeta");
                writer.Line("{");
                writer.Line($"    StableID = global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(stableName)}),");
                writer.Line($"    StableName = {OdGenerationContext.StringLiteral(stableName)},");
                writer.Line($"    DisplayName = {OdGenerationContext.StringLiteral(definition.Name)},");
                string debugRpcMode = definition.InterfaceType == OdInterfaceType.PlayerInput
                    ? context.Project.Runtime.NetworkMode == OdNetworkMode.Lockstep
                        ? "Lockstep"
                        : definition.Prediction == OdPredictionMode.None ? "Authority" : "Predictable"
                    : "None";
                writer.Line($"    RpcMode = global::GMCore.GameplayRpcMode.{debugRpcMode},");
                writer.Line($"    InterfaceType = global::GMCore.GameplayInterfaceType.{definition.InterfaceType},");
                writer.Line($"    IsRoutine = {(definition.IsRoutine ? "true" : "false")},");
                writer.Line($"    ParamType = typeof({scope}.{name}Param),");
                bool hasResult = !definition.IsRoutine &&
                                 definition.InterfaceType == OdInterfaceType.Gameplay;
                writer.Line($"    ResultType = {(hasResult ? $"typeof({scope}.{name}Result)" : "null")},");
                writer.Line($"    Inputs = {DebugInterfaceFields(context, context.AllInterfaceInputs(definition))},");
                writer.Line($"    Outputs = {DebugInterfaceFields(context, definition.Outputs)},");
                writer.Line($"    Invoke = InvokeDebug_{definition.Id:N},");
                writer.Line("};");
            }
            writer.Line("yield break;");
        }

        foreach (OdInterfaceDefinition definition in context.OwnedDefinitions.OfType<OdInterfaceDefinition>().Where(item => !item.Abstract).OrderBy(item => item.Id))
            EmitDebugInvoker(writer, context, definition);
    }

    private static void EmitDebugInvoker(CodeWriter writer, OdGenerationContext context, OdInterfaceDefinition definition)
    {
        string name = OdGenerationContext.Identifier(definition.Name);
        string scope = $"global::{context.Namespace(definition)}";
        string paramType = $"{scope}.{name}Param";
        writer.Line();
        using (writer.Block($"private static global::GMCore.ODDebugInvocationResult InvokeDebug_{definition.Id:N}(global::GMCore.GameplayMachine machine, global::System.Collections.Generic.IReadOnlyDictionary<string, global::GMCore.GameplayDebugValue> inputs)"))
        {
            writer.Line($"{paramType} param = default;");
            foreach (OdFieldDefinition field in context.AllInterfaceInputs(definition))
            {
                string member = OdGenerationContext.Identifier(field.Name);
                string local = $"input_{field.Id:N}";
                string inputType = context.FieldTypeName(field,
                    includeNullable: !(field.NotNull && context.IsLiveClassReference(field)));
                using (writer.Block($"if (inputs.TryGetValue({OdGenerationContext.StringLiteral(field.Name)}, out global::GMCore.GameplayDebugValue? {local}) && {local} is not null)"))
                    writer.Line($"param.{member} = global::GMCore.GameplayDebugValueConverter.ConvertTo<{inputType}>({local}, machine, {DebugResourceOptions(context, field.Type)}, {(field.Type.Container == OdContainerKind.Dictionary ? DebugResourceOptions(context, DebugKeyType(field.Type)) : "null")});");
            }
            if (definition.IsRoutine)
            {
                writer.Line("global::GMCore.CheckableInterfaceResult execution = machine.Execute((global::GMCore.ICheckableRoutine)param, true);");
                writer.Line("return execution.Sussceeded ? global::GMCore.ODDebugInvocationResult.Success() : global::GMCore.ODDebugInvocationResult.Failure(execution.ErrorMessage.ToString());");
            }
            else if (definition.InterfaceType == OdInterfaceType.PlayerInput)
            {
                writer.Line("global::GMCore.CheckableInterfaceResult execution = machine.Execute((global::GMCore.IReplicatedInterface)param);");
                writer.Line("return execution.Sussceeded ? global::GMCore.ODDebugInvocationResult.Success() : global::GMCore.ODDebugInvocationResult.Failure(execution.ErrorMessage.ToString());");
            }
            else
            {
                writer.Line($"global::GMCore.CheckableInterfaceResult<{scope}.{name}Result> execution = machine.Execute<{scope}.{name}Result>(param);");
                writer.Line("return execution.Sussceeded ? global::GMCore.ODDebugInvocationResult.Success(execution.Result) : global::GMCore.ODDebugInvocationResult.Failure(execution.ErrorMessage.ToString());");
            }
        }
    }

    private static string DebugInterfaceFields(OdGenerationContext context, IEnumerable<OdFieldDefinition> fields)
    {
        string values = string.Join(", ", fields.Select(field =>
            "new global::GMCore.ODDebugInterfaceFieldMeta { " +
            $"Name = {OdGenerationContext.StringLiteral(field.Name)}, DisplayName = {OdGenerationContext.StringLiteral(field.Name)}, " +
            $"ValueType = typeof({DebugValueTypeName(context, field.Type)}), " +
            $"KeyType = {(field.Type.Container == OdContainerKind.Dictionary ? $"typeof({DebugKeyTypeName(context, field.Type)})" : "null")}, " +
            $"Container = global::GMCore.GameplayDebugContainerKind.{DebugContainer(field.Type.Container)}, " +
            $"IsGameplayObjectReference = {(context.IsClassReference(field.Type) ? "true" : "false")}, " +
            $"GameplayObjectClassID = {DebugClassReferenceID(context, field.Type)}, " +
            $"IsResourceReference = {(DebugResourceDefinition(context, field.Type) is not null ? "true" : "false")}, " +
            $"IsResourceKeyReference = {(field.Type.Container == OdContainerKind.Dictionary && DebugResourceDefinition(context, DebugKeyType(field.Type)) is not null ? "true" : "false")}, " +
            $"ResourceOptions = {DebugResourceOptions(context, field.Type)}, " +
            $"ResourceKeyOptions = {(field.Type.Container == OdContainerKind.Dictionary ? DebugResourceOptions(context, DebugKeyType(field.Type)) : "null")}, " +
            $"NotNull = {(field.NotNull ? "true" : "false")} }}"));
        return $"new global::System.Collections.Generic.List<global::GMCore.ODDebugInterfaceFieldMeta> {{ {values} }}";
    }

    private static string DebugValueTypeName(OdGenerationContext context, OdTypeReference type)
    {
        var valueType = new OdTypeReference
        {
            BuiltIn = type.BuiltIn,
            DefinitionId = type.DefinitionId,
            IsResourceClass = type.IsResourceClass,
            Nullable = type.Nullable,
            Container = OdContainerKind.Single,
        };
        return context.TypeName(valueType, includeNullable: false);
    }

    private static string DebugKeyTypeName(OdGenerationContext context, OdTypeReference type)
    {
        var keyType = new OdTypeReference
        {
            BuiltIn = type.DictionaryKeyBuiltIn,
            DefinitionId = type.DictionaryKeyDefinitionId,
            IsResourceClass = type.DictionaryKeyIsResourceClass,
            Container = OdContainerKind.Single,
        };
        return context.TypeName(keyType, includeNullable: false);
    }

    private static OdTypeReference DebugKeyType(OdTypeReference type) => new()
    {
        BuiltIn = type.DictionaryKeyBuiltIn,
        DefinitionId = type.DictionaryKeyDefinitionId,
        IsResourceClass = type.DictionaryKeyIsResourceClass,
        Container = OdContainerKind.Single,
    };

    private static OdDefinition? DebugResourceDefinition(OdGenerationContext context, OdTypeReference type)
    {
        if (type.DefinitionId is not { } definitionId ||
            !context.Definitions.TryGetValue(definitionId, out OdDefinition? definition))
            return null;
        return definition is OdResourceDefinition || definition is OdClassDefinition && type.IsResourceClass
            ? definition
            : null;
    }

    private static string DebugResourceOptions(OdGenerationContext context, OdTypeReference type)
    {
        OdDefinition? definition = DebugResourceDefinition(context, type);
        if (definition is null)
            return "null";
        IEnumerable<(OdDataSet Folder, OdDataRecord Record)> records = context.Project.DataSets
            .Where(folder => folder.DefinitionId == definition.Id)
            .SelectMany(folder => folder.Records.Select(record => (Folder: folder, Record: record)))
            .OrderBy(item => item.Folder.Name, StringComparer.OrdinalIgnoreCase)
            .ThenBy(item => item.Record.Name, StringComparer.OrdinalIgnoreCase);
        string values = string.Join(", ", records.Select(item =>
            "new global::GMCore.ODDebugResourceOption { " +
            $"ID = new global::GMCore.ODResourceID(new global::System.Guid(\"{item.Record.Id:D}\")), " +
            $"Name = {OdGenerationContext.StringLiteral(item.Folder.Name + " / " + item.Record.Name)}, " +
            $"Value = {context.ResourceReferenceExpression(definition, item.Record.Id)} }}"));
        return $"new global::System.Collections.Generic.List<global::GMCore.ODDebugResourceOption> {{ {values} }}";
    }

    private static string DebugClassReferenceID(OdGenerationContext context, OdTypeReference type)
    {
        if (!context.IsClassReference(type) || type.DefinitionId is not { } definitionId ||
            !context.Definitions.TryGetValue(definitionId, out OdDefinition? definition) ||
            definition is not OdClassDefinition classDefinition)
            return "0UL";
        return $"global::GMCore.ODSaveHash.Compute({OdGenerationContext.StringLiteral(context.ClassStableName(classDefinition))})";
    }

    private static string DebugContainer(OdContainerKind container) => container switch
    {
        OdContainerKind.List => "List",
        OdContainerKind.Set => "Set",
        OdContainerKind.Dictionary => "Map",
        _ => "Single",
    };

    private static string BuildDebugSchemaSignature(OdGenerationContext context)
    {
        var parts = new List<string> { "od-debug:5", context.ModuleStableName,
            $"root:{context.Project.RootClassId?.ToString("N") ?? "none"}" };
        foreach (OdDefinition definition in context.OwnedDefinitions.OrderBy(item => item.Id))
        {
            parts.Add($"{definition.Kind}:{definition.Id:N}:{definition.Name}");
            if (definition is OdClassDefinition classDefinition)
                parts.Add($"is-classes:{string.Join(",", classDefinition.IsClasses.Select(id => id.ToString("N")))}");
            if (definition is OdFieldContainerDefinition fieldContainer)
                AddFields(parts, fieldContainer.Fields, includeReplication: definition is OdClassDefinition);
            if (definition is OdInterfaceDefinition interfaceDefinition)
            {
                parts.Add($"type:{interfaceDefinition.InterfaceType}:prediction:{interfaceDefinition.Prediction}:routine:{interfaceDefinition.IsRoutine}:abstract:{interfaceDefinition.Abstract}:base:{interfaceDefinition.BaseInterfaceId?.ToString("N") ?? "none"}");
                AddFields(parts, interfaceDefinition.Inputs);
                AddFields(parts, interfaceDefinition.Outputs);
            }
        }
        return string.Join("|", parts);
    }

    private static string RpcStableName(OdGenerationContext context, OdInterfaceDefinition definition) =>
        $"{context.ModuleStableName}:rpc:{definition.Id:N}";

    private static string BuildNetworkSchemaSignature(OdGenerationContext context)
    {
        var parts = context.Project.Runtime.NetworkMode == OdNetworkMode.Lockstep
            ? new List<string> { "od-network:12", context.ModuleStableName, "synchronization:Lockstep" }
            : new List<string> { "od-network:11", context.ModuleStableName };
        foreach (var definition in context.OwnedDefinitions.OrderBy(item => item.Id))
        {
            parts.Add($"definition:{definition.Kind}:{definition.Id:N}");
            switch (definition)
            {
                case OdClassDefinition classDefinition:
                    OdObjectPartitionMode partitionMode = context.Project.Runtime.NetworkMode == OdNetworkMode.Lockstep
                        ? OdObjectPartitionMode.Manual
                        : classDefinition.Partition;
                    parts.Add($"class:{classDefinition.Replication}:{classDefinition.Relevancy}:{partitionMode}:{string.Join(",", classDefinition.IsClasses.Select(id => id.ToString("N")))}");
                    AddFields(parts, classDefinition.Fields, includeReplication: true);
                    break;
                case OdStructDefinition structDefinition:
                    if (structDefinition.IsStructOf is not null)
                        parts.Add($"is-struct:{TypeIdentity(structDefinition.IsStructOf)}");
                    AddFields(parts, structDefinition.Fields);
                    break;
                case OdResourceDefinition resourceDefinition:
                    parts.Add("resource");
                    AddFields(parts, resourceDefinition.Fields);
                    break;
                case OdSwitchStructDefinition switchStructDefinition:
                    parts.Add("switch-struct");
                    AddFields(parts, switchStructDefinition.Fields);
                    break;
                case OdEnumDefinition enumDefinition:
                    foreach (var member in enumDefinition.Members.OrderBy(item => item.Id))
                        parts.Add($"enum:{member.Id:N}:{member.Value}");
                    break;
                case OdInterfaceDefinition interfaceDefinition when !interfaceDefinition.Abstract && interfaceDefinition.InterfaceType == OdInterfaceType.PlayerInput:
                    parts.Add($"type:PlayerInput:prediction:{interfaceDefinition.Prediction}:base:{interfaceDefinition.BaseInterfaceId?.ToString("N") ?? "none"}");
                    AddFields(parts, context.AllInterfaceInputs(interfaceDefinition));
                    break;
                case OdInterfaceDefinition interfaceDefinition:
                    parts.Add($"type:{interfaceDefinition.InterfaceType}:routine:{interfaceDefinition.IsRoutine}:abstract:{interfaceDefinition.Abstract}:base:{interfaceDefinition.BaseInterfaceId?.ToString("N") ?? "none"}");
                    AddFields(parts, interfaceDefinition.Inputs);
                    AddFields(parts, interfaceDefinition.Outputs);
                    break;
                case OdEventDefinition eventDefinition:
                    parts.Add($"multicast:{eventDefinition.Multicast}");
                    AddFields(parts, eventDefinition.Fields);
                    break;
            }
        }
        return string.Join("|", parts);
    }

    private static void AddFields(ICollection<string> parts, IEnumerable<OdFieldDefinition> fields, bool includeReplication = false)
    {
        foreach (var field in fields.OrderBy(item => item.Id))
            parts.Add($"field:{field.Id:N}:{TypeIdentity(field.Type)}:not-null:{field.NotNull}:mode:{field.Mode}:driven-by:{string.Join(",", field.DrivenByFields.Order())}{(includeReplication ? $":replication:{field.Replication}" : string.Empty)}");
    }

    private static string FieldReferences(
        OdGenerationContext context,
        IEnumerable<(OdClassDefinition Owner, OdFieldDefinition Field)> fields) =>
        string.Join(", ", fields.Select(item =>
            $"{context.FullName(item.Owner)}.Fields.{OdGenerationContext.Identifier(item.Field.Name)}"));

    private static string TypeIdentity(OdTypeReference type) =>
        $"{type.Container}:{type.Nullable}:{type.BuiltIn}:{type.DefinitionId?.ToString("N") ?? "none"}:{type.IsResourceClass}:" +
        $"{type.DictionaryKeyBuiltIn}:{type.DictionaryKeyDefinitionId?.ToString("N") ?? "none"}:{type.DictionaryKeyIsResourceClass}";

    private sealed class CodecWriter(CodeWriter writer, OdGenerationContext context)
    {
        private int _local;

        public void Write(OdFieldDefinition field, string expression, bool classNotNull = false) =>
            Write(field.Type, expression, classNotNull, context.ClassResourceDefinition(field));

        public string Read(OdFieldDefinition field, bool classNotNull = false) =>
            Read(field.Type, classNotNull, context.ClassResourceDefinition(field));

        public void Write(OdTypeReference type, string expression, bool classNotNull = false,
            OdClassDefinition? classResource = null)
        {
            classResource ??= context.ResourceClassDefinition(type);
            if (type.Container != OdContainerKind.Single)
            {
                WriteCollection(type, expression, classResource);
                return;
            }
            if (classResource is not null)
            {
                if (type.Nullable)
                {
                    writer.Line($"writer.WriteBoolean({expression} != null);");
                    using (writer.Block($"if ({expression} != null)"))
                        writer.Line(context.ClassResourceWriteStatement(classResource, expression) ??
                                    $"writer.WriteResourceID(global::{context.RootNamespace}.GeneratedResources.GetId({expression}));");
                }
                else
                {
                    writer.Line(context.ClassResourceWriteStatement(classResource, expression) ??
                                $"writer.WriteResourceID(global::{context.RootNamespace}.GeneratedResources.GetId({expression}));");
                }
                return;
            }
            if (type.DefinitionId is { } customDefinitionId &&
                context.Definitions.TryGetValue(customDefinitionId, out var customDefinition) &&
                context.UsesCustomSerialization(customDefinition))
            {
                writer.Line(context.CustomWriteStatement(customDefinition, expression) ??
                            $"writer.WriteCustom(typeof({context.TypeName(type, false)}), {expression});");
                return;
            }
            if (context.IsClassReference(type))
            {
                if (classNotNull)
                {
                    writer.Line($"if (!{expression}.ObjectID.IsValid) throw new global::System.InvalidOperationException(\"NotNull gameplay object reference cannot be null.\");");
                    writer.Line($"writer.WriteObjectID({expression}.ObjectID);");
                    return;
                }
                writer.Line($"writer.WriteBoolean({expression}.HasValue);");
                using (writer.Block($"if ({expression}.HasValue)"))
                    writer.Line($"writer.WriteObjectID({expression}.Value.ObjectID);");
                return;
            }
            if (type.Nullable && IsResourceReference(type))
            {
                writer.Line($"writer.WriteBoolean({expression} != null);");
                using (writer.Block($"if ({expression} != null)"))
                    Write(SingleWithoutNullable(type), expression);
                return;
            }
            if (type.Nullable && IsValueLike(type))
            {
                writer.Line($"writer.WriteBoolean({expression}.HasValue);");
                using (writer.Block($"if ({expression}.HasValue)"))
                    Write(SingleWithoutNullable(type), expression + ".Value");
                return;
            }
            if (type.DefinitionId is { } definitionId && context.Definitions.TryGetValue(definitionId, out var definition))
            {
                switch (definition)
                {
                    case OdClassDefinition:
                        writer.Line($"writer.WriteObjectID({expression}.ObjectID);");
                        return;
                    case OdEnumDefinition:
                        writer.Line($"writer.WriteVarInt32((int){expression});");
                        return;
                    case OdStructDefinition structDefinition:
                        if (structDefinition.IsStructOf is { } aliasType)
                        {
                            Write(aliasType, $"{expression}.Value");
                            return;
                        }
                        foreach (var field in structDefinition.Fields)
                            Write(field, $"{expression}.{OdGenerationContext.Identifier(field.Name)}");
                        return;
                    case OdResourceDefinition:
                        writer.Line($"writer.WriteResourceID(global::{context.RootNamespace}.GeneratedResources.GetId({expression}));");
                        return;
                    case OdSwitchStructDefinition switchStructDefinition:
                        WriteSwitchStruct(switchStructDefinition, expression);
                        return;
                }
            }
            if (context.Project.Runtime.NetworkMode == OdNetworkMode.Lockstep &&
                type.BuiltIn is OdBuiltInType.Single or OdBuiltInType.Double or OdBuiltInType.Decimal)
            {
                writer.Line($"writer.WriteInt64({expression}.RawValue);");
                return;
            }
            switch (type.BuiltIn)
            {
                case OdBuiltInType.Boolean: writer.Line($"writer.WriteBoolean({expression});"); break;
                case OdBuiltInType.Int32: writer.Line($"writer.WriteVarInt32({expression});"); break;
                case OdBuiltInType.Int64: writer.Line($"writer.WriteVarInt64({expression});"); break;
                case OdBuiltInType.Single: writer.Line($"writer.WriteSingle({expression});"); break;
                case OdBuiltInType.Double: writer.Line($"writer.WriteDouble({expression});"); break;
                case OdBuiltInType.Decimal: writer.Line($"writer.WriteDecimal({expression});"); break;
                case OdBuiltInType.String: writer.Line($"writer.WriteString({expression});"); break;
                case OdBuiltInType.DateTime: writer.Line($"writer.WriteInt64({expression}.ToBinary());"); break;
                default: writer.Line($"writer.WriteCustom(typeof({context.TypeName(type, false)}), {expression});"); break;
            }
        }

        public string Read(OdTypeReference type, bool classNotNull = false,
            OdClassDefinition? classResource = null)
        {
            classResource ??= context.ResourceClassDefinition(type);
            if (type.Container != OdContainerKind.Single)
                return ReadCollection(type, classResource);
            if (classResource is not null)
            {
                string expression = context.ClassResourceReadExpression(classResource) ??
                                    $"global::{context.RootNamespace}.GeneratedResources.Resolve<{context.ClassResourceTypeName(classResource)}>(reader.ReadResourceID())";
                if (type.Nullable)
                {
                    string variable = NewLocal("resource");
                    writer.Line($"{context.ClassResourceTypeName(classResource)}? {variable} = null;");
                    using (writer.Block("if (reader.ReadBoolean())"))
                        writer.Line($"{variable} = {expression};");
                    return variable;
                }
                return classNotNull ? RequireValue(expression, context.ClassResourceTypeName(classResource)) : expression;
            }
            if (type.DefinitionId is { } customDefinitionId &&
                context.Definitions.TryGetValue(customDefinitionId, out var customDefinition) &&
                context.UsesCustomSerialization(customDefinition))
            {
                string expression = context.CustomReadExpression(customDefinition) ??
                                    $"reader.ReadCustom<{context.TypeName(type, false)}>()";
                return classNotNull ? RequireValue(expression, context.TypeName(type, false)) : expression;
            }
            if (context.IsClassReference(type))
            {
                if (classNotNull)
                {
                    string required = NewLocal("gameplayObject");
                    string objectId = NewLocal("objectId");
                    writer.Line($"global::GMCore.GObjectID {objectId} = reader.ReadObjectID();");
                    writer.Line($"if (!{objectId}.IsValid) throw new global::System.IO.InvalidDataException(\"NotNull gameplay object reference cannot be null.\");");
                    writer.Line($"{context.TypeName(type, false)} {required} = default;");
                    writer.Line($"{required}.Machine = reader.Machine;");
                    writer.Line($"{required}.ObjectID = {objectId};");
                    return required;
                }
                string variable = NewLocal("gameplayObjectReference");
                writer.Line($"{context.TypeName(type)} {variable} = null;");
                using (writer.Block("if (reader.ReadBoolean())"))
                {
                    string actual = NewLocal("gameplayObject");
                    writer.Line($"{context.TypeName(type, false)} {actual} = default;");
                    writer.Line($"{actual}.Machine = reader.Machine;");
                    writer.Line($"{actual}.ObjectID = reader.ReadObjectID();");
                    writer.Line($"{variable} = {actual};");
                }
                return variable;
            }
            if (type.Nullable && IsResourceReference(type))
            {
                string variable = NewLocal("resource");
                writer.Line($"{context.TypeName(type)} {variable} = null;");
                using (writer.Block("if (reader.ReadBoolean())"))
                    writer.Line($"{variable} = {Read(SingleWithoutNullable(type))};");
                return variable;
            }
            if (type.Nullable && IsValueLike(type))
            {
                string variable = NewLocal("nullable");
                writer.Line($"{context.TypeName(type)} {variable} = null;");
                using (writer.Block("if (reader.ReadBoolean())"))
                {
                    string actual = Read(SingleWithoutNullable(type));
                    writer.Line($"{variable} = {actual};");
                }
                return variable;
            }
            if (type.DefinitionId is { } definitionId && context.Definitions.TryGetValue(definitionId, out var definition))
            {
                switch (definition)
                {
                    case OdClassDefinition:
                        {
                            string variable = NewLocal("gameplayObject");
                            writer.Line($"{context.TypeName(type)} {variable} = default;");
                            writer.Line($"{variable}.Machine = reader.Machine;");
                            writer.Line($"{variable}.ObjectID = reader.ReadObjectID();");
                            return variable;
                        }
                    case OdEnumDefinition:
                        return $"({context.TypeName(type)})reader.ReadVarInt32()";
                    case OdStructDefinition structDefinition:
                        {
                            string variable = NewLocal("structure");
                            string initializer = context.IsReferenceType(structDefinition)
                                ? $"new {context.TypeName(type, false)}()"
                                : "default";
                            writer.Line($"{context.TypeName(type)} {variable} = {initializer};");
                            if (structDefinition.IsStructOf is { } aliasType)
                            {
                                string aliasValue = Read(aliasType);
                                writer.Line($"{variable}.Value = {aliasValue};");
                                return variable;
                            }
                            foreach (var field in structDefinition.Fields)
                            {
                                string child = Read(field);
                                writer.Line($"{variable}.{OdGenerationContext.Identifier(field.Name)} = {child};");
                            }
                            return variable;
                        }
                    case OdResourceDefinition:
                        {
                            string expression = $"global::{context.RootNamespace}.GeneratedResources.Resolve<{context.TypeName(type, false)}>(reader.ReadResourceID())";
                            return classNotNull ? RequireValue(expression, context.TypeName(type, false)) : expression;
                        }
                    case OdSwitchStructDefinition switchStructDefinition:
                        return ReadSwitchStruct(switchStructDefinition, type);
                }
            }
            if (context.Project.Runtime.NetworkMode == OdNetworkMode.Lockstep &&
                type.BuiltIn is OdBuiltInType.Single or OdBuiltInType.Double or OdBuiltInType.Decimal)
                return "global::XLockstep.Fixed64.FromRaw(reader.ReadInt64())";
            return type.BuiltIn switch
            {
                OdBuiltInType.Boolean => "reader.ReadBoolean()",
                OdBuiltInType.Int32 => "reader.ReadVarInt32()",
                OdBuiltInType.Int64 => "reader.ReadVarInt64()",
                OdBuiltInType.Single => "reader.ReadSingle()",
                OdBuiltInType.Double => "reader.ReadDouble()",
                OdBuiltInType.Decimal => "reader.ReadDecimal()",
                OdBuiltInType.String => "reader.ReadString()",
                OdBuiltInType.DateTime => "global::System.DateTime.FromBinary(reader.ReadInt64())",
                _ => $"reader.ReadCustom<{context.TypeName(type, false)}>()",
            };
        }

        private void WriteCollection(OdTypeReference type, string expression, OdClassDefinition? classResource)
        {
            writer.Line($"writer.WriteCount({expression} == null ? -1 : {expression}.Count);");
            using (writer.Block($"if ({expression} != null)"))
            {
                if (type.Container == OdContainerKind.Dictionary)
                {
                    string item = NewLocal("item");
                    using (writer.Block($"foreach (global::System.Collections.Generic.KeyValuePair<{context.DictionaryKeyTypeName(type)}, {ElementTypeName(type, classResource)}> {item} in {expression})"))
                    {
                        Write(DictionaryKeyReference(type), $"{item}.Key", classNotNull: true);
                        Write(ElementReference(type), $"{item}.Value", classResource: classResource);
                    }
                }
                else
                {
                    string item = NewLocal("item");
                    using (writer.Block($"foreach ({ElementTypeName(type, classResource)} {item} in {expression})"))
                        Write(ElementReference(type), item, classResource: classResource);
                }
            }
        }

        private void WriteSwitchStruct(OdSwitchStructDefinition definition, string expression)
        {
            string typeName = context.FullName(definition);
            writer.Line($"writer.WriteVarInt32((int){expression}.SwitchType);");
            using (writer.Block($"switch ({expression}.SwitchType)"))
            {
                foreach (OdFieldDefinition field in definition.Fields)
                {
                    string fieldName = OdGenerationContext.Identifier(field.Name);
                    using (writer.Block($"case {typeName}.SwitchTypes.{fieldName}:"))
                    {
                        Write(field, $"{expression}.{fieldName}");
                        writer.Line("break;");
                    }
                }
                using (writer.Block("default:"))
                    writer.Line("throw new global::System.IO.InvalidDataException(\"Unknown switch struct subtype\");");
            }
        }

        private string ReadSwitchStruct(OdSwitchStructDefinition definition, OdTypeReference type)
        {
            string typeName = context.FullName(definition);
            string variable = NewLocal("switchStruct");
            string discriminator = NewLocal("switchType");
            writer.Line($"{context.TypeName(type)} {variable} = default;");
            writer.Line($"{typeName}.SwitchTypes {discriminator} = ({typeName}.SwitchTypes)reader.ReadVarInt32();");
            using (writer.Block($"switch ({discriminator})"))
            {
                foreach (OdFieldDefinition field in definition.Fields)
                {
                    string fieldName = OdGenerationContext.Identifier(field.Name);
                    using (writer.Block($"case {typeName}.SwitchTypes.{fieldName}:"))
                    {
                        string child = Read(field);
                        writer.Line($"{variable}.{fieldName} = {child};");
                        writer.Line("break;");
                    }
                }
                using (writer.Block("default:"))
                    writer.Line("throw new global::System.IO.InvalidDataException(\"Unknown switch struct subtype\");");
            }
            return variable;
        }

        private string ReadCollection(OdTypeReference type, OdClassDefinition? classResource)
        {
            string count = NewLocal("count");
            string collection = NewLocal("collection");
            writer.Line($"int {count} = reader.ReadCount();");
            string collectionType = context.TypeName(type);
            writer.Line($"{collectionType} {collection} = null!;");
            using (writer.Block($"if ({count} >= 0)"))
            {
                string constructor = $"new {context.CollectionStorageTypeName(type)}()";
                writer.Line($"{collection} = {constructor};");
                string index = NewLocal("i");
                using (writer.Block($"for (int {index} = 0; {index} < {count}; {index}++)"))
                {
                    if (type.Container == OdContainerKind.Dictionary)
                    {
                        OdTypeReference keyType = DictionaryKeyReference(type);
                        string keyExpression = Read(keyType, classNotNull: true);
                        string key = NewLocal("key");
                        writer.Line($"{context.TypeName(keyType, includeNullable: false)} {key} = {keyExpression};");
                        string value = Read(ElementReference(type), classResource: classResource);
                        writer.Line($"{collection}.Add({key}, {value});");
                    }
                    else
                    {
                        string value = Read(ElementReference(type), classResource: classResource);
                        writer.Line($"{collection}.Add({value});");
                    }
                }
            }
            return collection;
        }

        private string ElementTypeName(OdTypeReference type, OdClassDefinition? classResource) =>
            classResource is null ? context.TypeName(ElementReference(type)) : context.ClassResourceTypeName(classResource) + "?";
        private static OdTypeReference ElementReference(OdTypeReference type) => new()
        {
            BuiltIn = type.BuiltIn,
            DefinitionId = type.DefinitionId,
            IsResourceClass = type.IsResourceClass,
            Container = OdContainerKind.Single,
            Nullable = false,
        };
        private static OdTypeReference DictionaryKeyReference(OdTypeReference type) => new()
        {
            BuiltIn = type.DictionaryKeyBuiltIn,
            DefinitionId = type.DictionaryKeyDefinitionId,
            IsResourceClass = type.DictionaryKeyIsResourceClass,
            Container = OdContainerKind.Single,
        };
        private static OdTypeReference SingleWithoutNullable(OdTypeReference type) => new()
        {
            BuiltIn = type.BuiltIn,
            DefinitionId = type.DefinitionId,
            IsResourceClass = type.IsResourceClass,
            Container = OdContainerKind.Single,
            Nullable = false,
        };
        private bool IsValueLike(OdTypeReference type)
        {
            if (type.DefinitionId is { } id && context.Definitions.TryGetValue(id, out var definition))
                return definition is OdStructDefinition or OdSwitchStructDefinition or OdEnumDefinition;
            return type.BuiltIn != OdBuiltInType.String;
        }
        private bool IsResourceReference(OdTypeReference type) =>
            type.DefinitionId is { } id && context.Definitions.TryGetValue(id, out var definition) &&
            definition is OdResourceDefinition;
        private static string RequireValue(string expression, string typeName) =>
            $"({expression} ?? throw new global::System.IO.InvalidDataException(\"Required resource '{typeName}' cannot be null.\"))";
        private string NewLocal(string prefix) => prefix + _local++;
    }
}
