using ODStudio.Model;

namespace ODStudio.Generator;

internal static class OdRuntimeEmitter
{
    public static string Emit(OdProject project)
    {
        string rootNamespace = OdGenerationContext.NamespaceIdentifier(project.DefaultNamespace);
        string projectName = OdProjectCodeManager.SafeProjectName(project);
        var modules = project.Ods.OrderBy(item => item.Namespace, StringComparer.Ordinal)
            .Select(scope => $"new global::{OdGenerationContext.NamespaceIdentifier(scope.Namespace)}.{OdGenerationContext.SafeIdentifier(scope.Name)}Module()")
            .ToArray();
        var scenes = project.Scenes.OrderBy(item => item.Name, StringComparer.Ordinal)
            .Select(scene =>
            {
                OdScope? scope = project.FindOd(scene);
                string ns = OdGenerationContext.NamespaceIdentifier(scope?.Namespace ?? project.DefaultNamespace);
                string type = OdGenerationContext.SafeIdentifier(scene.Name) + "Scene";
                return $"[{StringLiteral(scene.Name)}] = global::{ns}.{type}.Instance";
            }).ToArray();
        OdClassDefinition? rootDefinition = project.RootClassId is { } rootClassId
            ? project.Definitions.FirstOrDefault(item => item.Id == rootClassId) as OdClassDefinition
            : null;
        string rootType = rootDefinition is null
            ? string.Empty
            : $"global::{OdGenerationContext.NamespaceIdentifier(rootDefinition.Namespace)}.{OdGenerationContext.SafeIdentifier(rootDefinition.Name)}";
        string rootClass = rootDefinition is null ? "null" : rootType + ".ClassName";
        string initialScene = project.InitialSceneId is { } initialSceneId &&
                              project.Scenes.FirstOrDefault(item => item.Id == initialSceneId) is OdScene initial
            ? $"global::{OdGenerationContext.NamespaceIdentifier(project.FindOd(initial)?.Namespace ?? project.DefaultNamespace)}.{OdGenerationContext.SafeIdentifier(initial.Name)}Scene.Instance"
            : "null";

        var writer = new CodeWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();
        using (writer.Block($"namespace {rootNamespace}"))
        {
            using (writer.Block($"public partial class {projectName}GameplayMachine : global::GMCore.GameplayMachine"))
            {
                using (writer.Block("protected override global::GMCore.GameplayMachine.GameplayMachineProxy CreateGameplayMachineProxy()"))
                    writer.Line($"return new {projectName}GameplayMachineProxy(this);");
                if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                {
                    writer.Line();
                    writer.Line("public new global::GMCore.Lockstep.PlayerController? LocalPlayerController => base.LocalLockstepPlayerController;");
                    using (writer.Block("public new global::System.Collections.Generic.IEnumerable<global::GMCore.Lockstep.PlayerController> GetPlayerControllers()"))
                        writer.Line("return base.GetLockstepPlayerControllers();");
                    using (writer.Block("public new global::GMCore.Lockstep.PlayerController GetLocalPlayerController()"))
                        writer.Line("return base.GetLocalLockstepPlayerController();");
                }
                if (rootDefinition is not null)
                {
                    writer.Line();
                    using (writer.Block($"public new {rootType} GetRoot()"))
                        writer.Line($"return base.GetRoot().Cast<{rootType}>() ?? throw new global::System.InvalidOperationException(\"GameplayMachine root is not a {rootDefinition.Name}\");");
                }
                if (project.Runtime.NetworkMode == OdNetworkMode.StateSync && project.Runtime.ProvisionPartitions)
                {
                    writer.Line();
                    using (writer.Block("internal void ProvisionConfiguredPartitions(global::GMCore.Position center, float range)"))
                        writer.Line("OnProvisionPartitions(center, range);");
                }
                if (project.Runtime.NetworkMode == OdNetworkMode.StateSync && project.Runtime.PartitionResolver == OdPartitionResolverKind.Custom)
                {
                    writer.Line();
                    using (writer.Block("internal void QueryConfiguredPartitions(global::GMCore.Position center, float range, global::System.Collections.Generic.ISet<global::GMCore.PartitionID> results)"))
                        writer.Line("OnQueryPartitions(center, range, results);");
                    using (writer.Block("internal bool TryResolveConfiguredPartition(global::GMCore.Position position, out global::GMCore.PartitionID partition)"))
                        writer.Line("return TryResolvePartition(position, out partition);");
                }
            }
            writer.Line();
            using (writer.Block($"public sealed class {projectName}GameplayMachineProxy : global::GMCore.GameplayMachine.GameplayMachineProxy"))
            {
                using (writer.Block($"public {projectName}GameplayMachineProxy({projectName}GameplayMachine machine) : base(machine)"))
                {
                }
                if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                {
                    writer.Line();
                    writer.Line("public new global::GMCore.Lockstep.PlayerController? LocalPlayerController => base.LocalLockstepPlayerController;");
                    using (writer.Block("public new global::System.Collections.Generic.IEnumerable<global::GMCore.Lockstep.PlayerController> GetPlayerControllers()"))
                        writer.Line("return base.GetLockstepPlayerControllers();");
                    using (writer.Block("public new global::GMCore.Lockstep.PlayerController GetLocalPlayerController()"))
                        writer.Line("return base.GetLocalLockstepPlayerController();");
                    using (writer.Block("public bool TryGetExecutingPlayerController(out global::GMCore.Lockstep.PlayerController playerController)"))
                        writer.Line("return base.TryGetExecutingLockstepPlayerController(out playerController);");
                    using (writer.Block("public new global::GMCore.Lockstep.PlayerController GetExecutingPlayerController()"))
                        writer.Line("return base.GetExecutingLockstepPlayerController();");
                }
                if (rootDefinition is not null)
                {
                    writer.Line();
                    using (writer.Block($"public new {rootType} GetRoot()"))
                        writer.Line($"return base.GetRoot().Cast<{rootType}>() ?? throw new global::System.InvalidOperationException(\"GameplayMachine root is not a {rootDefinition.Name}\");");
                }
            }
            writer.Line();
            if (project.Runtime.NetworkMode == OdNetworkMode.StateSync && project.Runtime.PartitionResolver == OdPartitionResolverKind.Custom)
            {
                using (writer.Block($"internal sealed class {projectName}PartitionResolver : global::GMCore.IGameplayPartitionResolver"))
                {
                    using (writer.Block("public void Query(global::GMCore.GameplayMachine machine, global::GMCore.Position center, float range, global::System.Collections.Generic.ISet<global::GMCore.PartitionID> results)"))
                        writer.Line($"(({projectName}GameplayMachine)machine).QueryConfiguredPartitions(center, range, results);");
                    using (writer.Block("public bool TryResolve(global::GMCore.GameplayMachine machine, global::GMCore.Position position, out global::GMCore.PartitionID partition)"))
                        writer.Line($"return (({projectName}GameplayMachine)machine).TryResolveConfiguredPartition(position, out partition);");
                }
                writer.Line();
            }
            using (writer.Block($"public sealed class {projectName}Runtime : global::GMCore.IODGameplayRuntime"))
            {
                writer.Line($"public string Name => {StringLiteral(project.Name)};");
                using (writer.Block("public global::GMCore.GameplayMachineSettings CreateSettings()"))
                {
                    writer.Line("var settings = new global::GMCore.GameplayMachineSettings();");
                    writer.Line($"settings.GameplayMachineFactory = () => new {projectName}GameplayMachine();");
                    writer.Line($"settings.SynchronizationMode = global::GMCore.GameplaySynchronizationMode.{project.Runtime.NetworkMode};");
                    string tickMode = project.Runtime.NetworkMode == OdNetworkMode.StateSync &&
                                      project.Runtime.StateSyncTickMode == OdStateSyncTickMode.None
                        ? "None"
                        : "FixedRate";
                    writer.Line($"settings.TickMode = global::GMCore.GameplayTickMode.{tickMode};");
                    writer.Line($"settings.TickIntervalMilliseconds = {project.Runtime.TickIntervalMilliseconds};");
                    writer.Line("settings.Interest = new global::GMCore.GameplayInterestSettings");
                    writer.Line("{");
                    writer.Line($"    CellSize = {FloatLiteral(project.Runtime.SpatialCellSize)},");
                    if (project.Runtime.NetworkMode == OdNetworkMode.StateSync && project.Runtime.PartitionResolver == OdPartitionResolverKind.Grid)
                        writer.Line($"    PartitionResolver = new global::GMCore.GameplayGridPartitionResolver({FloatLiteral(project.Runtime.PartitionCellSize)}, includeY: {project.Runtime.PartitionIncludeY.ToString().ToLowerInvariant()}),");
                    else if (project.Runtime.NetworkMode == OdNetworkMode.StateSync && project.Runtime.PartitionResolver == OdPartitionResolverKind.Custom)
                        writer.Line($"    PartitionResolver = new {projectName}PartitionResolver(),");
                    if (project.Runtime.NetworkMode == OdNetworkMode.StateSync && project.Runtime.ProvisionPartitions)
                        writer.Line($"    ProvisionPartitions = (machine, center, range) => (({projectName}GameplayMachine)machine).ProvisionConfiguredPartitions(center, range),");
                    writer.Line($"    LoadMargin = {FloatLiteral(project.Runtime.LoadMargin)},");
                    writer.Line($"    UnloadDelaySeconds = {FloatLiteral(project.Runtime.UnloadDelaySeconds)},");
                    writer.Line($"    MaxLoadsPerUpdate = {project.Runtime.MaxLoadsPerUpdate},");
                    writer.Line($"    ManagePartitionLoading = {(project.Runtime.NetworkMode == OdNetworkMode.StateSync && project.Runtime.ManagePartitionLoading).ToString().ToLowerInvariant()},");
                    writer.Line("};");
                    writer.Line($"settings.RootGameplayObjectClass = {rootClass};");
                    writer.Line($"settings.InitialScene = {initialScene};");
                    writer.Line("return settings;");
                }
                using (writer.Block("public global::System.Collections.Generic.IReadOnlyList<global::GMCore.IODModule> CreateModules()"))
                    writer.Line($"return new global::GMCore.IODModule[] {{ {string.Join(", ", modules)} }};");
                writer.Line("public global::System.Collections.Generic.IReadOnlyDictionary<string, global::GMCore.IODScene> Scenes { get; } =");
                writer.Line("    new global::System.Collections.Generic.Dictionary<string, global::GMCore.IODScene>(global::System.StringComparer.OrdinalIgnoreCase)");
                writer.Line("    {");
                foreach (string scene in scenes)
                    writer.Line($"        {scene},");
                writer.Line("    };");
            }
            writer.Line();
            using (writer.Block($"public enum {projectName}LaunchMode"))
            {
                writer.Line("Offline,");
                writer.Line("Host,");
                writer.Line("DedicatedServer,");
                writer.Line("ClientProxy,");
                writer.Line("LockstepClient,");
            }
            writer.Line();
            using (writer.Block($"public sealed class {projectName}GameOptions"))
            {
                string defaultLaunchMode = project.Runtime.NetworkMode == OdNetworkMode.Lockstep
                    ? "LockstepClient"
                    : "Offline";
                writer.Line($"public {projectName}LaunchMode Mode {{ get; set; }} = {projectName}LaunchMode.{defaultLaunchMode};");
                writer.Line("public string Address { get; set; } = \"0.0.0.0\";");
                writer.Line("public int Port { get; set; } = 7777;");
                writer.Line("public int RequestedSlot { get; set; }");
                writer.Line("public bool EnableDebugServer { get; set; }");
                writer.Line("public string DebugAddress { get; set; } = \"0.0.0.0\";");
                writer.Line("public int DebugPort { get; set; } = 7788;");
                writer.Line("public string DebugToken { get; set; } = string.Empty;");
                writer.Line("public global::XLogger.Logger? Logger { get; set; }");
                writer.Line("public string LogDirectory { get; set; } = \"logs\";");
                writer.Line($"public string LogFilePrefix {{ get; set; }} = \"{projectName}\";");
                writer.Line("public bool WriteLogsToConsole { get; set; } = true;");
                writer.Line("public bool UseDelayedCallbacks { get; set; } = true;");
                writer.Line("public byte[]? SaveData { get; set; }");
                writer.Line("public global::GMCore.GameplayNetworkOptions? NetworkOptions { get; set; }");
                writer.Line("public global::GMCore.GameplayLockstepOptions? LockstepOptions { get; set; }");
                if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                {
                    writer.Line("public bool StartRelayServer { get; set; }");
                    writer.Line("public string RelayAddress { get; set; } = \"127.0.0.1\";");
                    writer.Line("public string RelayListenAddress { get; set; } = \"0.0.0.0\";");
                    writer.Line("public int RelayPort { get; set; } = 7777;");
                    writer.Line("public int RelayPlayerCount { get; set; } = 2;");
                    writer.Line("public string? RelayRecordingDirectory { get; set; }");
                }
            }
            writer.Line();
            using (writer.Block($"public sealed class {projectName}GameHost : global::System.IDisposable"))
            {
                writer.Line("private bool _disposed;");
                writer.Line("private readonly global::System.IDisposable? _ownedLogger;");
                if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                    writer.Line("private readonly global::GMCore.GameplayLockstepRelayServer? _relayServer;");
                writer.Line($"public {projectName}GameplayMachine Machine {{ get; }}");
                writer.Line();
                string hostConstructor = project.Runtime.NetworkMode == OdNetworkMode.Lockstep
                    ? $"private {projectName}GameHost({projectName}GameplayMachine machine, global::GMCore.GameplayLockstepRelayServer? relayServer, global::System.IDisposable? ownedLogger)"
                    : $"private {projectName}GameHost({projectName}GameplayMachine machine, global::System.IDisposable? ownedLogger)";
                using (writer.Block(hostConstructor))
                {
                    writer.Line("Machine = machine;");
                    writer.Line("_ownedLogger = ownedLogger;");
                    if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                        writer.Line("_relayServer = relayServer;");
                }
                writer.Line();
                using (writer.Block($"public static {projectName}GameHost Start({projectName}GameOptions? options = null)"))
                {
                    writer.Line($"options ??= new {projectName}GameOptions();");
                    writer.Line($"var runtime = new {projectName}Runtime();");
                    writer.Line("global::GMCore.GameplayMachineSettings settings = runtime.CreateSettings();");
                    writer.Line("global::System.IDisposable? ownedLogger = null;");
                    writer.Line("if (options.Logger is not null)");
                    writer.Line("    settings.Logger = options.Logger;");
                    writer.Line("else if (settings.Logger is null)");
                    writer.Line("{");
                    writer.Line("    var logger = new global::GMCore.GameplayLogger(new global::GMCore.GameplayLoggerOptions");
                    writer.Line("    {");
                    writer.Line("        DirectoryPath = options.LogDirectory,");
                    writer.Line("        FilePrefix = options.LogFilePrefix,");
                    writer.Line("        WriteToConsole = options.WriteLogsToConsole,");
                    writer.Line("    });");
                    writer.Line("    settings.Logger = logger;");
                    writer.Line("    ownedLogger = logger;");
                    writer.Line("}");
                    writer.Line($"settings.LocalPlayerMode = options.Mode == {projectName}LaunchMode.DedicatedServer");
                    writer.Line("    ? global::GMCore.GameplayLocalPlayerMode.Disabled");
                    writer.Line("    : global::GMCore.GameplayLocalPlayerMode.Enabled;");
                    writer.Line("global::GMCore.IODModule[] modules = global::System.Linq.Enumerable.ToArray(runtime.CreateModules());");
                    writer.Line("global::GMCore.GameplayMachine rawMachine;");
                    writer.Line($"if (options.Mode == {projectName}LaunchMode.ClientProxy)");
                    writer.Line("    rawMachine = global::GMCore.GameplayMachineBase.CreateClientProxy(null, settings, modules);");
                    writer.Line("else if (options.SaveData is not null)");
                    writer.Line("    rawMachine = global::GMCore.GameplayMachineBase.LoadGameplayMachine(new global::GMCore.MachineKey { ID = -1 }, settings, options.SaveData, modules);");
                    writer.Line("else");
                    writer.Line("    rawMachine = global::GMCore.GameplayMachineBase.SpawnGameplayMachine(null, settings, modules);");
                    writer.Line($"var machine = ({projectName}GameplayMachine)rawMachine;");
                    writer.Line("machine.SetUseDelayedCallback(options.UseDelayedCallbacks);");
                    if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                        writer.Line("global::GMCore.GameplayLockstepRelayServer? relayServer = null;");
                    writer.Line("try");
                    writer.Line("{");
                    writer.Line($"    if (options.Mode == {projectName}LaunchMode.Host || options.Mode == {projectName}LaunchMode.DedicatedServer)");
                    writer.Line("    {");
                    writer.Line("        global::System.Net.IPAddress address = ResolveAddress(options.Address, true);");
                    writer.Line("        var transport = global::GMCore.LiteNetLibGameplayNetworkTransport.CreateServer(new global::System.Net.IPEndPoint(address, options.Port));");
                    writer.Line("        machine.EnableNetworking(transport, options.NetworkOptions);");
                    writer.Line("        settings.Logger.Log(global::XLogger.LogVerbosity.Common, global::GMCore.LogCatagories.Runner, $\"{options.Mode} listening on {address}:{options.Port}\");");
                    writer.Line("    }");
                    writer.Line($"    else if (options.Mode == {projectName}LaunchMode.ClientProxy)");
                    writer.Line("    {");
                    writer.Line("        var transport = global::GMCore.LiteNetLibGameplayNetworkTransport.CreateClient(options.Address, options.Port);");
                    writer.Line("        machine.ConnectNetworking(transport, options.NetworkOptions);");
                    writer.Line("        settings.Logger.Log(global::XLogger.LogVerbosity.Common, global::GMCore.LogCatagories.Runner, $\"Connecting ClientProxy to {options.Address}:{options.Port}\");");
                    writer.Line("    }");
                    writer.Line($"    else if (options.Mode == {projectName}LaunchMode.LockstepClient)");
                    writer.Line("    {");
                    writer.Line("        global::GMCore.GameplayLockstepOptions lockstep = options.LockstepOptions ?? new global::GMCore.GameplayLockstepOptions();");
                    writer.Line("        lockstep.Logger ??= settings.Logger;");
                    writer.Line("        lockstep.TickIntervalMilliseconds = settings.TickIntervalMilliseconds;");
                    writer.Line("        lockstep.RequestedSlot = options.RequestedSlot;");
                    writer.Line($"        lockstep.TickMode = global::GMCore.GameplayLockstepTickMode.{project.Runtime.LockstepTickMode};");
                    if (project.Runtime.LockstepTickMode == OdLockstepTickMode.InputDriven)
                        writer.Line("        lockstep.InputDelayTicks = 0;");
                    if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                    {
                        writer.Line("        string relayAddress = options.RelayAddress;");
                        writer.Line("        if (options.StartRelayServer)");
                        writer.Line("        {");
                        writer.Line("            if (!IsLoopbackAddress(options.RelayAddress))");
                        writer.Line("                throw new global::System.InvalidOperationException(\"RelayAddress cannot specify a remote server when StartRelayServer is enabled.\");");
                        writer.Line("            if (options.RelayPlayerCount <= 0)");
                        writer.Line("                throw new global::System.ArgumentOutOfRangeException(nameof(options.RelayPlayerCount));");
                        writer.Line("            lockstep.ExpectedPlayerCount = options.RelayPlayerCount;");
                        writer.Line("            if (!string.IsNullOrWhiteSpace(options.RelayRecordingDirectory))");
                        writer.Line("                lockstep.RecordingDirectory = options.RelayRecordingDirectory;");
                        writer.Line("            global::System.Net.IPAddress listenAddress = ResolveAddress(options.RelayListenAddress, true);");
                        writer.Line("            relayServer = new global::GMCore.GameplayLockstepRelayServer(");
                        writer.Line("                global::GMCore.LiteNetLibGameplayNetworkTransport.CreateServer(new global::System.Net.IPEndPoint(listenAddress, options.RelayPort)), lockstep);");
                        writer.Line("            relayServer.Start();");
                        writer.Line("            settings.Logger.Log(global::XLogger.LogVerbosity.Common, global::GMCore.LogCatagories.Runner, $\"Embedded Lockstep relay listening on {listenAddress}:{options.RelayPort}; expected players={options.RelayPlayerCount}\");");
                        writer.Line("            relayAddress = \"127.0.0.1\";");
                        writer.Line("        }");
                        writer.Line("        var transport = global::GMCore.LiteNetLibGameplayNetworkTransport.CreateClient(relayAddress, options.RelayPort);");
                    }
                    else
                        writer.Line("        var transport = global::GMCore.LiteNetLibGameplayNetworkTransport.CreateClient(options.Address, options.Port);");
                    writer.Line("        machine.ConnectLockstepNetworking(transport, lockstep);");
                    if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                        writer.Line("        settings.Logger.Log(global::XLogger.LogVerbosity.Common, global::GMCore.LogCatagories.Runner, $\"Connecting Lockstep peer to {relayAddress}:{options.RelayPort}\");");
                    else
                        writer.Line("        settings.Logger.Log(global::XLogger.LogVerbosity.Common, global::GMCore.LogCatagories.Runner, $\"Connecting Lockstep peer to {options.Address}:{options.Port}\");");
                    writer.Line("    }");
                    writer.Line("    if (options.EnableDebugServer)");
                    writer.Line("        machine.StartDebugServer(new global::GMCore.GameplayDebugOptions");
                    writer.Line("        {");
                    writer.Line("            Address = options.DebugAddress,");
                    writer.Line("            Port = options.DebugPort,");
                    writer.Line("            Token = options.DebugToken,");
                    writer.Line("            Access = global::GMCore.GameplayDebugAccess.Control,");
                    writer.Line("        });");
                    writer.Line(project.Runtime.NetworkMode == OdNetworkMode.Lockstep
                        ? $"    return new {projectName}GameHost(machine, relayServer, ownedLogger);"
                        : $"    return new {projectName}GameHost(machine, ownedLogger);");
                    writer.Line("}");
                    writer.Line("catch");
                    writer.Line("{");
                    writer.Line("    machine.DisableNetworking();");
                    if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                        writer.Line("    relayServer?.Dispose();");
                    writer.Line("    ownedLogger?.Dispose();");
                    writer.Line("    throw;");
                    writer.Line("}");
                }
                writer.Line();
                using (writer.Block("public void Update(double deltaSeconds)"))
                {
                    if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                        writer.Line("_relayServer?.Update();");
                    writer.Line("Machine.Update(deltaSeconds);");
                    if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                        writer.Line("_relayServer?.Update();");
                }
                writer.Line();
                using (writer.Block("public byte[] Save()"))
                    writer.Line("return global::GMCore.GameplayMachineBase.SaveGameplayMachine(Machine);");
                writer.Line();
                using (writer.Block("public void Dispose()"))
                {
                    writer.Line("if (_disposed) return;");
                    writer.Line("_disposed = true;");
                    writer.Line("Machine.StopDebugServer();");
                    writer.Line("Machine.DisableNetworking();");
                    if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                        writer.Line("_relayServer?.Dispose();");
                    writer.Line("Machine.Logger.Log(global::XLogger.LogVerbosity.Common, global::GMCore.LogCatagories.Runner, \"GameplayMachine host disposed\");");
                    writer.Line("_ownedLogger?.Dispose();");
                }
                writer.Line();
                using (writer.Block("private static global::System.Net.IPAddress ResolveAddress(string value, bool allowAny)"))
                {
                    writer.Line("if (allowAny && (string.IsNullOrWhiteSpace(value) || value == \"0.0.0.0\"))");
                    writer.Line("    return global::System.Net.IPAddress.Any;");
                    writer.Line("if (global::System.Net.IPAddress.TryParse(value, out global::System.Net.IPAddress? parsed))");
                    writer.Line("    return parsed;");
                    writer.Line("return global::System.Linq.Enumerable.First(global::System.Net.Dns.GetHostAddresses(value), item => item.AddressFamily == global::System.Net.Sockets.AddressFamily.InterNetwork);");
                }
                if (project.Runtime.NetworkMode == OdNetworkMode.Lockstep)
                {
                    writer.Line();
                    using (writer.Block("private static bool IsLoopbackAddress(string value)"))
                    {
                        writer.Line("if (string.Equals(value, \"localhost\", global::System.StringComparison.OrdinalIgnoreCase)) return true;");
                        writer.Line("return global::System.Net.IPAddress.TryParse(value, out global::System.Net.IPAddress? address) && global::System.Net.IPAddress.IsLoopback(address);");
                    }
                }
            }
        }
        return writer.ToString();
    }

    private static string StringLiteral(string value) =>
        "\"" + (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string FloatLiteral(float value) =>
        value.ToString("R", global::System.Globalization.CultureInfo.InvariantCulture) + "f";
}
