using System.Text.Json.Nodes;
using ODStudio.Model;

namespace ODStudio.Generator;

internal static class OdSceneEmitter
{
    public static string Emit(OdGenerationContext context)
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();
        using (writer.Block($"namespace {context.RootNamespace}"))
        {
            foreach (OdScene scene in context.OwnedScenes.OrderBy(item => item.Name, StringComparer.Ordinal))
            {
                EmitScene(writer, context, scene);
                writer.Line();
            }
        }
        return writer.ToString();
    }

    private static void EmitScene(CodeWriter writer, OdGenerationContext context, OdScene scene)
    {
        string sceneType = OdGenerationContext.SafeIdentifier(scene.Name) + "Scene";
        using (writer.Block($"public sealed class {sceneType} : global::GMCore.IODScene"))
        {
            writer.Line($"public static readonly {sceneType} Instance = new {sceneType}();");
            using (writer.Block("public static class Objects"))
                foreach (OdSceneObject sceneObject in scene.Objects)
                    writer.Line($"public static readonly global::System.Guid {OdGenerationContext.SafeIdentifier(sceneObject.Name)} = new global::System.Guid(\"{sceneObject.Id:D}\");");
            writer.Line();
            using (writer.Block("public void Create(global::GMCore.GameplayMachine.GameplayMachineProxy machine, global::GMCore.GameplaySceneInstance instance)"))
            {
                var variables = new Dictionary<Guid, string>();
                foreach (OdSceneObject sceneObject in scene.Objects)
                {
                    if (!context.Definitions.TryGetValue(sceneObject.ClassDefinitionId, out OdDefinition? definition) ||
                        definition is not OdClassDefinition classDefinition)
                        continue;
                    string variable = "object_" + sceneObject.Id.ToString("N");
                    variables[sceneObject.Id] = variable;
                    writer.Line($"{context.FullName(classDefinition)} {variable} = machine.CreateGameplayObject<{context.FullName(classDefinition)}>();");
                    writer.Line($"instance.Register(Objects.{OdGenerationContext.SafeIdentifier(sceneObject.Name)}, {variable});");
                }
                if (variables.Count > 0)
                    writer.Line();

                foreach (OdSceneObject sceneObject in scene.Objects)
                {
                    if (!variables.TryGetValue(sceneObject.Id, out string? variable) ||
                        !context.Definitions.TryGetValue(sceneObject.ClassDefinitionId, out OdDefinition? definition) ||
                        definition is not OdClassDefinition classDefinition)
                        continue;
                    foreach (var (_, field) in context.AllFields(classDefinition).Where(item => item.Field.Mode != OdFieldMode.Driven))
                    {
                        if (!sceneObject.Values.TryGetValue(field.Id, out JsonNode? configured) && field.DefaultValue is null)
                            continue;
                        JsonNode? value = configured ?? field.DefaultValue;
                        string literal = SceneLiteral(context, scene, variables, field.Type, value, sceneObject.Id);
                        string member = OdGenerationContext.Identifier(field.Name);
                        if (field.Type.Container == OdContainerKind.Single)
                            writer.Line($"{variable}.{member} = {literal};");
                        else
                            writer.Line($"{variable}.{member}.AddRange({literal});");
                    }
                }
            }
        }
    }

    private static string SceneLiteral(OdGenerationContext context, OdScene scene,
        IReadOnlyDictionary<Guid, string> variables, OdTypeReference type, JsonNode? value, Guid targetId)
    {
        if (value is null)
            return type.Container == OdContainerKind.Single ? "null" : $"new {context.TypeName(type, false)}()";
        var elementType = new OdTypeReference
        {
            BuiltIn = type.BuiltIn,
            DefinitionId = type.DefinitionId,
            IsResourceClass = type.IsResourceClass,
            Nullable = type.Nullable,
        };
        if (type.Container is OdContainerKind.List or OdContainerKind.Set && value is JsonArray array)
        {
            string items = string.Join(", ", array.Select(item => SceneLiteral(context, scene, variables, elementType, item, targetId)));
            return $"new {context.TypeName(type, false)} {{ {items} }}";
        }
        if (type.Container == OdContainerKind.Dictionary && value is JsonObject map)
        {
            var keyType = new OdTypeReference
            {
                BuiltIn = type.DictionaryKeyBuiltIn,
                DefinitionId = type.DictionaryKeyDefinitionId,
                IsResourceClass = type.DictionaryKeyIsResourceClass,
            };
            string items = string.Join(", ", map.Select(item =>
                $"[{context.JsonLiteral(keyType, JsonValue.Create(item.Key), targetId)}] = {SceneLiteral(context, scene, variables, elementType, item.Value, targetId)}"));
            return $"new {context.TypeName(type, false)} {{ {items} }}";
        }
        if (type.Container == OdContainerKind.Single &&
            (type.DefinitionId is { } definitionId &&
             context.Definitions.TryGetValue(definitionId, out OdDefinition? definition) &&
             definition is OdClassDefinition && !type.IsResourceClass))
        {
            if (value is JsonValue reference && reference.TryGetValue<string>(out string? text) &&
                Guid.TryParse(text, out Guid objectId) && variables.TryGetValue(objectId, out string? variable))
                return variable;
            return "null";
        }
        return context.JsonLiteral(type, value, targetId);
    }
}
