using ODStudio.Model;

namespace ODStudio.Generator;

internal static class OdStaticDataEmitter
{
    public static string Emit(OdGenerationContext context)
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();
        using (writer.Block($"namespace {context.RootNamespace}"))
        {
            using (writer.Block("public static class GeneratedResources"))
            {
                EmitResources(writer, context);
            }
        }
        return writer.ToString();
    }

    private static void EmitResources(CodeWriter writer, OdGenerationContext context)
    {
        var records = context.OwnedDataSets.OrderBy(item => item.Name, StringComparer.Ordinal)
            .SelectMany(folder => folder.Records.OrderBy(item => item.Name, StringComparer.Ordinal)
                .Select(record => (Folder: folder, Record: record,
                    Definition: context.Definitions.GetValueOrDefault(folder.DefinitionId))))
            .Where(item => item.Definition is OdClassDefinition or OdResourceDefinition)
            .ToList();
        foreach (var item in records)
        {
            string type = ResourceTypeName(context, item.Definition!);
            string name = ResourceMemberName(item.Folder, item.Record);
            if (context.Options.ResourceReferenceExpression is not null)
                writer.Line($"public static {type} {name} => {context.ResourceReferenceExpression(item.Definition!, item.Record.Id)};");
            else
                writer.Line($"public static {type} {name} {{ get; private set; }} = null!;");
        }
        if (context.Options.ResourceReferenceExpression is not null)
            return;
        if (records.Count > 0)
        {
            writer.Line();
            using (writer.Block("static GeneratedResources()"))
            {
                foreach (var item in records)
                    writer.Line($"{ResourceMemberName(item.Folder, item.Record)} = new {ResourceTypeName(context, item.Definition!)}();");
                foreach (var item in records)
                {
                    OdFieldContainerDefinition container = (OdFieldContainerDefinition)item.Definition!;
                    IEnumerable<OdFieldDefinition> fields = item.Definition is OdClassDefinition classDefinition
                        ? context.AllFields(classDefinition).Select(field => field.Field)
                        : container.Fields;
                    foreach (OdFieldDefinition field in fields.Where(field => field.Mode != OdFieldMode.Driven &&
                                                                               !context.IsLiveClassReference(field)))
                    {
                        string value = item.Record.Values.TryGetValue(field.Id, out var json)
                            ? context.JsonLiteral(field.Type, json, item.Record.Id)
                            : context.DefaultExpression(field);
                        writer.Line($"{ResourceMemberName(item.Folder, item.Record)}.{OdGenerationContext.Identifier(field.Name)} = {value};");
                    }
                }
            }
        }

        writer.Line();
        using (writer.Block("public static global::GMCore.ODResourceID GetId(object? value)"))
        {
            writer.Line("if (value is null) return default;");
            foreach (var item in records)
                writer.Line($"if (global::System.Object.ReferenceEquals(value, {ResourceMemberName(item.Folder, item.Record)})) return new global::GMCore.ODResourceID(new global::System.Guid(\"{item.Record.Id:D}\"));");
            writer.Line("throw new global::System.InvalidOperationException(\"Resource is not part of the generated OD resource catalog.\");");
        }
        using (writer.Block("public static T? Resolve<T>(global::GMCore.ODResourceID id) where T : class"))
        {
            writer.Line("if (!id.IsValid) return null;");
            foreach (var item in records)
                writer.Line($"if (id == new global::GMCore.ODResourceID(new global::System.Guid(\"{item.Record.Id:D}\"))) return {ResourceMemberName(item.Folder, item.Record)} as T ?? throw new global::System.IO.InvalidDataException(\"OD resource type does not match the requested type.\");");
            writer.Line("throw new global::System.IO.InvalidDataException($\"OD resource '{id}' is not part of the generated resource catalog.\");");
        }
    }

    private static string ResourceTypeName(OdGenerationContext context, OdDefinition definition) =>
        definition is OdClassDefinition classDefinition
            ? context.ClassResourceTypeName(classDefinition)
            : context.FullName(definition);

    private static string ResourceMemberName(OdDataSet folder, OdDataRecord record) =>
        OdGenerationContext.SafeIdentifier(folder.Name) + "_" + OdGenerationContext.SafeIdentifier(record.Name);
}
