<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>gameplaymachine-editor</AssemblyName>
    <Product>GameplayMachine Editor CLI</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\gameplaymachine_core\main\GameplayMachineCore\GameplayMachineCore.csproj" />
    <ProjectReference Include="..\ODStudio.Export\ODStudio.Export.csproj" />
    <ProjectReference Include="..\ODStudio.Export.Unity\ODStudio.Export.Unity.csproj" />
    <ProjectReference Include="..\ODStudio.Generator\ODStudio.Generator.csproj" />
    <ProjectReference Include="..\ODStudio.Model\ODStudio.Model.csproj" />
    <ProjectReference Include="..\ODStudio.Package\ODStudio.Package.csproj" />
  </ItemGroup>
</Project>
